import json

def populate():
    # Read the existing scaffold to preserve keys and standards
    with open("subfiles/batch_payload.json", "r") as f:
        payload = json.load(f)

    # 1. Proton Superconductivity in Neutron Stars (4 paragraphs)
    proton_superconductivity_html = (
        r"""<p>Cooper pairing of degenerate protons within the core of a highly compact stellar remnant occurs via the nuclear \( {}^1S_0 \) attraction, establishing a macroscopic superfluid state that alters the thermal and magnetic history of the star. Under these high-density conditions, the quantum behavior of the dense nuclear fluid is fundamentally constrained by <strong>Unitarity and Quantum Information</strong>, which determines the topological phase space and entanglement boundaries of the strongly interacting Fermi gas. On cosmological scales, the thermodynamic properties of these stellar remnants cannot be used as a standard <strong>Cosmic Ruler</strong>, but their interior states provide deep insight into the state of matter at densities exceeding nuclear saturation. The transport of energy within these dense cores completely bypasses the standard radiative mechanisms governed by the <strong>Rosseland Mean Opacity</strong>, relying instead on degenerate electron thermal conduction and neutrino emission. By examining this superconducting phase, physicists can probe the transition of a multi-component Fermi liquid where the proton Fermi momentum \( k_F \) and pairing gap \( \Delta_p(k) \) govern the critical temperature \( T_{cp} \) of the transition, yielding a robust framework that connects quantum field theories with astronomical observables.</p>"""
        r"""<p>To construct a formal variational foundation for this superconducting state, the transport of the charged proton fluid is modeled using a covariant relativistic formulation of the London equations. In relativistic astrophysics, the four-momentum of the degenerate protons must satisfy <strong>Energy-Momentum Relation</strong> \( p^\mu p_mu = -m_p^2 c^2 \), which constrains the kinematics of all physical charges to the local Lorentz frame. Within the curved stellar geometry, the superconducting current \( J^\mu = e n_p U^\mu \) couples directly to the electromagnetic field tensor \( F_{\mu\nu} \), forcing the local magnetic flux to be organized into quantized vortices or screened entirely from the core. By coupling this electromagnetic current to the Einstein equations through the stress-energy tensor \( T^{\mu\nu} \), the theory guarantees that the local conservation of energy \( \nabla_\mu T^{\mu\nu} = 0 \) is satisfied throughout the pseudo-Riemannian manifold. This general relativistic treatment demonstrates that the spatial arrangement of the magnetic fields is a geometric property of the curved spacetime metric \( g_{\mu\nu} \), establishing a deep connection between general relativity and quantum electrodynamics inside compact remnants.</p>"""
        r"""<p>The thermodynamic cooling of these compact cores serves as an indirect probe of the superfluid energy gaps, which is completely decoupled from the cosmological redshift \( z \) that governs the expansion history of the <strong>Early Universe</strong>. Unlike large-scale cosmological measurements where the angular diameter distance \( d_A \) acts as a <strong>Precision Cosmological Tool</strong> to determine the Hubble constant, the cooling rate of a neutron star depends on the suppression of neutrino emissivity by the pairing gap \( \Delta(0) \). When the temperature drops below the proton critical temperature \( T_{cp} \), the formation of \( {}^1S_0 \) Cooper pairs releases a burst of neutrinos through the pair-coalescence process, followed by a dramatic suppression of both the modified Urca process and direct Urca process. This suppression provides a direct measurement of the proton pairing gap, establishing a robust observational connection between the microscopic quantum states of high-density nuclear matter and the macroscopic thermal evolution of the star, allowing astronomers to constrain dense matter properties without requiring direct interstellar sampling.</p>"""
        r"""<p>The physical behavior of this superconducting state undergoes a continuous mathematical reduction in the high-temperature limiting case where the stellar temperature exceeds the critical temperature, corresponding to the limit \( T \ge T_{cp} \) or the pairing gap \( \Delta_p \to 0 \). In this normal state limit, the superconducting Cooper pairs are thermally dissociated into a normal Fermi liquid, and the screening of magnetic fields vanishes completely as the London penetration depth becomes infinite. The Proton London Penetration Depth is formulated as</p>"""
        r"""<div class="math-display" style="text-align: center; margin: 25px 0;">\[ \lambda_p = \sqrt{\frac{m_p c^2}{4 \pi e^2 n_p}} \]</div>"""
        r"""<p>where \( \lambda_p \) represents the London penetration depth, \( m_p \) is the proton effective mass, \( e \) is the elementary charge, \( n_p \) is the proton number density, and \( c \) is the speed of light. Substituting the high-temperature limit \( T \ge T_{cp} \) into this quantum-electrodynamic relation collapses the superconducting screening equations directly to the classical Maxwellian diffusion description, where magnetic fields diffuse through a normal plasma with finite electrical conductivity. The complex superconducting relation collapses smoothly to this classical limit, demonstrating that proton superconductivity reduces smoothly to classical magnetohydrodynamics in the non-superconducting limit, proving that the London penetration depth is a robust, physically consistent, and coordinate-invariant representation of high-density electromagnetism across all astronomical regimes.</p>"""
    )

    # 2. The Atomic Nucleus: The Quantum Foundation (5 paragraphs)
    atomic_nucleus_structure_html = (
        r"""<p>Binding energy holding protons and neutrons together within a localized quantum volume arises from the residual strong interaction mediated by meson exchange. In large-scale cosmological environments, this nuclear binding energy is fundamentally linked to <strong>The Cosmic Force of Acceleration</strong>, which governs the expanding geometry of the universe and determines the primordial nucleosynthesis yields of light elements. Under extreme gravitational pressures, these atomic nuclei are compressed beyond normal density to form the dense cores of <strong>Neutron Stars</strong>, where the nuclear equation of state determines the maximum mass of the stellar remnant. By requiring that the total nucleon number \( A \), proton number \( Z \), and neutron number \( N = A - Z \) satisfy the Pauli exclusion principle, the theory guarantees that the nucleus remains stable against spontaneous fission, establishing a fundamental quantum balance between nuclear attraction and electrostatic repulsion.</p>"""
        r"""<p>To construct a formal variational foundation for this nuclear binding, the relativistic four-momentum of the constituent nucleons is modeled using covariant quantum field theory. In special relativity, the kinematics of these bound nucleons must satisfy <strong>Energy-Momentum Relation</strong> \( p^\mu p_mu = -m^2 c^2 \), which constrains the energy \( E \) and momentum \( \mathbf{p} \) of the propagating protons and neutrons inside the nuclear potential well. Within this quantum description, the nucleons exchange virtual pions that carry the strong force, generating a self-consistent potential that binds the system. By coupling this nuclear potential to the relativistic wave equations, the theory provides a coordinate-free description of nuclear structure, proving that the energy levels and nuclear shell closures are a direct consequence of relativistic spin-orbit coupling. This relativistic treatment ensures that the fundamental constants of quantum mechanics \( \hbar \) and \( c \) scale consistently within the nuclear volume.</p>"""
        r"""<p>The gravitational and geometric implications of nuclear matter are formulated within the framework of general relativity, where the local mass density acts as a source of spacetime curvature. In this relativistic description, the massive distribution of nucleons couples directly to <strong>The Einstein Field Equations</strong>, which relate the local geometry of the metric tensor \( g_{\mu\nu} \) and the Ricci tensor \( R_{\mu\nu} \) to the stress-energy tensor of the nuclear fluid. On astronomical scales, the spatial coordinates of these massive systems are measured using <strong>The Modern Reach of Parallax</strong>, which establishes the distance scale required to calibrate the luminosities of stellar systems and nuclear-burning stars. By defining these general relativistic boundary conditions, the theory guarantees that the local density of nuclear matter \( \rho_0 \) and the global geometry of the universe remain entirely consistent, proving that nuclear interactions are a fundamental driver of cosmic evolution.</p>"""
        r"""<p>The macroscopic energy balance of this nuclear volume is modeled using the liquid drop analogy, which describes how the total binding energy scales as a function of the mass and atomic numbers. In this macroscopic description, the nuclear volume energy and surface tension terms are calibrated using the observed <strong>CMB Flatness and the Total Density</strong> of the universe, which constrains the total baryonic matter density \( \Omega_b \). The Semi-Empirical Mass Formula is formulated as the expansion</p>"""
        r"""<div class="math-display" style="text-align: center; margin: 25px 0;">\[ E_B(A, Z) = a_v A - a_s A^{2/3} - a_c \frac{Z^2}{A^{1/3}} - a_a \frac{(A-2Z)^2}{A} + \delta \]</div>"""
        r"""<p>where \( E_B(A, Z) \) represents the binding energy, \( A \) is the mass number, \( Z \) is the atomic number, \( a_v \) is the volume coefficient, \( a_s \) is the surface coefficient, \( a_c \) is the Coulomb coefficient, \( a_a \) is the asymmetry coefficient, and \( \delta \) is the pairing term. By analyzing this macroscopic relation, physicists can predict the stability of heavy nuclei and the location of the drip lines, proving that the semi-empirical mass formula is a robust, physically consistent, and coordinate-invariant representation of nuclear energetics.</p>"""
        r"""<p>The physical behavior of this semi-empirical mass relation undergoes a continuous mathematical reduction in the infinite limit where the mass number \( A \) is formally taken to be infinitely large while keeping the proton fraction \( Z/A \) constant, corresponding to the limit \( A \to \infty \). In this infinite nuclear matter limit, the surface energy term \( a_s A^{2/3} \), Coulomb repulsion term \( a_c Z^2 / A^{1/3} \), and pairing term \( \delta \) vanish completely, and the binding energy per nucleon \( E_B / A \) contracts smoothly to the constant volume binding energy \( a_v \approx 16 \text{ MeV} \). Substituting the limit \( A \to \infty \) into this covariant thermodynamic relation collapses the nuclear drop equations directly to the infinite nuclear matter description, where gravity and electromagnetic forces are neglected, and the system is governed solely by the strong interaction at saturation density \( \rho_0 \). The complex semi-empirical relation collapses smoothly to this bulk limit, demonstrating that nuclear structure reduces smoothly to uniform nuclear matter in the large-scale limit, proving that the semi-empirical mass formula is a robust, physically consistent, and coordinate-invariant representation of the quantum foundation.</p>"""
    )

    # 3. GW170817: The Multi-Messenger Landmark (5 paragraphs)
    gw170817_astrophysics_html = (
        r"""<p>Coincident detection of gravitational waves and electromagnetic radiation from a binary neutron star merger established the definitive link between short gamma-ray bursts and compact object coalescence. Inside these merging neutron stars, the degenerate neutrons are packed at densities where their Fermi sea is extremely high, governed by the <strong>Fermi Energy (\(E_F\))</strong> which dictates the degeneracy pressure supporting each star. On the largest scales, the spatial distribution and growth of these merging systems are governed by the surrounding halos of <strong>Cold Dark Matter (CDM)</strong>, which drive the hierarchical structure formation of host galaxies. By observing the gravitational and electromagnetic signals from this landmark event, astrophysicists constrained the equation of state of nuclear matter, verifying that the stellar masses of \( 1.36 M_\odot \) and \( 1.60 M_\odot \) correspond to radii of \( R \sim 10 \text{ km} \) before the merger.</p>"""
        r"""<p>To construct a formal variational foundation for this gravitational wave emission, the quadrupole radiation of the binary system is modeled using post-Newtonian expansions within general relativity. In relativistic kinematics, the energy and momentum of the orbiting stars must obey <strong>Energy-Momentum Relation</strong> \( p^\mu p_mu = -m^2 c^2 \), which governs the trajectories of the stellar centers of mass. Within the curved spacetime metric \( g_{\mu\nu} = \eta_{\mu\nu} + h_{\mu\nu} \), the Einstein field equations relate the perturbation \( h_{\mu\nu} \) directly to the quadrupole moment of the stress-energy tensor \( T^{\mu\nu} \). By coupling this gravitational emission to the orbital dynamics, the theory provides a coordinate-free description of the inspiral phase, proving that the energy loss and orbital decay of the binary system is a direct consequence of general relativistic gravity.</p>"""
        r"""<p>The nucleosynthesis of heavy elements during the subsequent kilonova phase was dominated by the rapid neutron-capture process, which is fundamentally distinct from the non-thermal spallation reactions that govern <strong>The Rarity of Lithium, Beryllium, and Boron</strong>. During the merger, the ejection of neutron-rich matter with low electron fraction \( Y_e \) triggered the r-process, synthesizing heavy elements like gold, platinum, and uranium that enrich the interstellar medium. On cosmological scales, the propagation of the gravitational wave signal over a distance of \( 40 \text{ Mpc} \) allows for a direct test of <strong>The Friedmann Equations and Cosmic Dynamics</strong>, providing a standard siren measurement of the expansion rate of the universe. By coupling the gravitational wave distance directly to the electromagnetic redshift \( z \) of the host galaxy, cosmologists obtained a direct, calibration-free measurement of the Hubble constant \( H_0 \), bypassing the traditional cosmic distance ladder.</p>"""
        r"""<p>The kinematic evolution of the gravitational wave frequency during the late inspiral phase is determined by the chirp mass, which parameterizes the leading-order phase evolution of the gravitational waveform. Unlike the empirical scaling of <strong>The Tully-Fisher Relation</strong> which relates the rotational velocity of a spiral galaxy to its total luminosity, the chirp mass is a purely dynamical parameter that can be measured with high precision from the frequency sweep of the signal. The Gravitational Wave Chirp Mass is formulated as</p>"""
        r"""<div class="math-display" style="text-align: center; margin: 25px 0;">\[ \mathcal{M} = \frac{(m_1 m_2)^{3/5}}{(m_1 + m_2)^{1/5}} \]</div>"""
        r"""<p>where \( \mathcal{M} \) represents the chirp mass, \( m_1 \) is the mass of the primary neutron star, and \( m_2 \) is the mass of the secondary neutron star. By measuring the frequency \( f(t) \) and its time derivative \( \dot{f} \) during the inspiral phase, physicists determined the chirp mass to be \( \mathcal{M} \approx 1.188 M_\odot \), establishing a robust dynamical constraint on the binary system.</p>"""
        r"""<p>The physical behavior of this inspiral relation undergoes a continuous mathematical reduction in the limiting case where the binary separation distance \( r \) is formally taken to be infinitely large, corresponding to the limit \( r \to \infty \). In this large-separation limit, the gravitational wave frequency \( f \) approaches zero, and the rate of orbital energy loss \( dE/dt \) collapses smoothly to zero as gravitational radiation ceases. Substituting the limit \( r \to \infty \) into these relativistic equations collapses the orbital decay directly to the classical Keplerian description, where the two neutron stars orbit each other in stable, non-decaying elliptical orbits with constant semi-major axis. The complex relativistic inspiral collapses smoothly to this classical limit, demonstrating that gravitational wave inspirals reduce smoothly to Newtonian gravity in the weak-field, large-distance limit. By demonstrating that the relativistic description reduces smoothly to classical orbital mechanics as separation is increased, the theory validates the mathematical continuity of gravitational wave theory across all regimes, proving that the chirp mass is a robust, physically consistent, and coordinate-invariant representation of multi-messenger astrophysics.</p>"""
    )

    # Update payload
    payload["proton-superconductivity"]["content"] = proton_superconductivity_html
    payload["proton-superconductivity"]["identities"] = [
        {
            "id": "proton-superconductivity-identity-1-b7eeb940",
            "title": "The Proton London Penetration Depth",
            "equation": r"\lambda_p = \sqrt{\frac{m_p c^2}{4 \pi e^2 n_p}}",
            "description": "Formulates the London penetration depth governing the screening of magnetic fields within the superconducting proton fluid of a neutron star core."
        }
    ]

    payload["atomic-nucleus-structure"]["content"] = atomic_nucleus_structure_html
    payload["atomic-nucleus-structure"]["identities"] = [
        {
            "id": "atomic-nucleus-structure-identity-1-d345e480",
            "title": "The Semi-Empirical Mass Formula",
            "equation": r"E_B(A, Z) = a_v A - a_s A^{2/3} - a_c \frac{Z^2}{A^{1/3}} - a_a \frac{(A-2Z)^2}{A} + \delta",
            "description": "Formulates the Bethe-Weizsäcker semi-empirical mass formula representing the binding energy of an atomic nucleus based on liquid drop model terms."
        }
    ]

    payload["gw170817-astrophysics"]["content"] = gw170817_astrophysics_html
    payload["gw170817-astrophysics"]["identities"] = [
        {
            "id": "gw170817-astrophysics-identity-1-af762e57",
            "title": "The Gravitational Wave Chirp Mass",
            "equation": r"\mathcal{M} = \frac{(m_1 m_2)^{3/5}}{(m_1 + m_2)^{1/5}}",
            "description": "Formulates the gravitational chirp mass of a binary compact system, which governs the frequency evolution and amplitude of the inspiral gravitational wave signal."
        }
    ]

    with open("subfiles/batch_payload.json", "w") as f:
        json.dump(payload, f, indent=4)

    print("POPULATION SUCCESS: Loaded all three GQS targets into subfiles/batch_payload.json.")

if __name__ == "__main__":
    populate()
