import json

def populate():
    # Read the existing scaffold to preserve keys and standards
    with open("subfiles/batch_payload.json", "r") as f:
        payload = json.load(f)

    # 1. Effective Potential and Central Forces Prose
    # Note: Use raw triple double quotes (r"""...""") and exactly two backslashes for MathJax delimiters
    effective_potential_mechanics_html = (
        r"""<p>Reduction of a two-dimensional central force problem to an equivalent one-dimensional radial system is mathematically accomplished by introducing a coordinate-dependent potential energy term that accounts for both the physical potential and the centrifugal kinetic energy of the orbiting body. When a particle of mass \( m \) moves under the influence of a spherically symmetric central potential \( V(r) \), its angular momentum vector \( \mathbf{L} \) is a conserved constant of motion, restricting the trajectory to a fixed plane perpendicular to \( \mathbf{L} \). In this planar configuration, the radial position vector \( \mathbf{r} \) and its time derivative \( \dot{\mathbf{r}} \) dictate the planar coordinates, allowing the kinetic energy to be split into radial and angular components. While the physical forces are spherically symmetric, the total electrostatic or gravitational potential in multi-source configurations can be analyzed using the principles of <strong>Source Summation (Superposition)</strong> to construct the global potential landscape. When these interactions occur in polarizing media, the effective forces are modified by the dielectric response, which is mathematically represented by <strong>The Electric Displacement Field (\(\mathbf{D}\))</strong>. The centrifugal energy term \( \frac{L^2}{2mr^2} \) acts as a repulsive barrier that prevents the particle from falling into the origin, provided the angular momentum \( L \) is non-zero, thus modifying the physical potential energy landscape.</p>"""
        r"""<p>To formalize the radial dynamics without explicitly resolving the angular coordinates, we combine the physical potential with the angular kinetic energy term to construct the effective potential function. This mathematical simplification yields the fundamental radial energy equation where the total mechanical energy \( E \) is expressed directly in terms of the radial velocity \( \dot{r} \), which serves as the physical generator of the classical trajectory. The coupled mechanical equations of motion are governed by the effective potential and physical constraints, formulated as"""
        r"""<div class="math-display" style="text-align: center; margin: 25px 0;">\[ V_{\text{eff}}(r) = V(r) + \frac{L^2}{2 m r^2} \]</div>"""
        r"""where the radial coordinate \( r \) parameterizes the distance from the force center, and \( m \) represents the inertial mass of the particle. The centrifugal term \( \frac{L^2}{2mr^2} \) acts as a fictitious potential that scales quadratically with the conserved angular momentum \( L \) and decays as \( r^{-2} \) at large radial distances. This elegant formulation demonstrates how a multi-dimensional mechanical problem can be mapped onto a one-dimensional system where the effective force \( F_{\text{eff}} = - \frac{d V_{\text{eff}}}{d r} \) governs the radial acceleration. The minimization of this potential energy functional determines the stable circular orbits, which can be derived from variational principles such as <strong>Least Action</strong> to locate the dynamic paths that extremize the physical action over time.</p>"""
        r"""<p>Analyzing the mechanical stability of circular orbits requires evaluating the local curvature of this effective potential energy surface at its critical points where the first derivative vanishes. For a circular orbit of radius \( r_0 \), the radial coordinate remains constant, requiring that the effective force vanishes, which establishes the equilibrium condition \( V_{\text{eff}}'(r_0) = 0 \). To determine whether this circular path is stable against small radial perturbations \( \delta r(t) = r(t) - r_0 \), we expand the effective potential using a <strong>Taylor Expansion and the Harmonic Approximation</strong> about the equilibrium radius. If the second derivative of the effective potential is positive, \( V_{\text{eff}}''(r_0) > 0 \), the perturbed particle undergoes stable, harmonic radial oscillations about \( r_0 \) with an angular frequency \( \omega_r = \sqrt{V_{\text{eff}}''(r_0)/m} \). The geometry of these orbits in phase space is bounded by energy surfaces whose gradient vectors are perpendicular to the curves of constant energy, demonstrating the geometric property of <strong>Perpendicularity to Level Surfaces</strong> for conservative mechanical systems.</p>"""
        r"""<p>The physical consequences of this radial reduction are beautifully illustrated in classical gravitational systems and electrostatic configurations where the force fields satisfy the inverse-square law. When we integrate the flux of these central field vectors over a closed boundary surface of volume \( V \) surrounding the source charge or mass \( q \), the net flux is determined solely by the enclosed source strength. This fundamental physical relationship is formalized mathematically by <strong>Gauss's (Divergence) Theorem</strong>, which relates the volume integral of the divergence \( \nabla \cdot \mathbf{E} \) of the field to the surface integral of the flux. In the context of the electrostatic field \( \mathbf{E} \) or gravitational field \( \mathbf{g} \), this divergence relation guarantees that the force field outside a spherically symmetric distribution \( \rho(r') \) is mathematically equivalent to that of a point source located at the origin. Consequently, the effective potential derived for a point-like central force remains perfectly valid for spherical bodies of finite radius, allowing celestial mechanics and atomic models to be formulated using identical radial equations of motion.</p>"""
        r"""<p>The physical behavior of this effective potential representation undergoes a continuous mechanical reduction in the limiting case where the angular momentum is formally taken to zero. In this zero-angular-momentum limit \( L \to 0 \), the centrifugal barrier term \( \frac{L^2}{2mr^2} \) vanishes identically at all non-zero radial positions, and the effective potential contracts smoothly to the bare physical potential \( V(r) \). The mechanical system loses its two-dimensional orbital features, and the trajectory collapses from a planar curve into a simple one-dimensional rectilinear line along the radial coordinate \( r \). Under these conditions, the particle no longer experiences the repulsive barrier and instead undergoes direct radial fall or unconstrained propagation toward or away from the force center, governed solely by the physical potential gradient \( -\frac{dV}{dr} \). By demonstrating that the effective potential contracts smoothly to the physical potential as the orbital constraints are removed, the theory establishes a mathematically rigorous and physically consistent bridge between orbital dynamics and linear mechanical motion, validating the general covariance of the radial description.</p>"""
    )

    # 2. Harmonic Expansion and Multipole Moments Prose
    harmonic_expansion_potential_html = (
        r"""<p>Representation of a localized charge distribution through a series of decoupled coordinate moments provides a powerful framework for evaluating potential fields at large asymptotic distances where the fine details of the source geometry are unresolved. When analyzing the electrostatic potential \( \Phi(\mathbf{r}) \) generated by a source charge density \( \rho(\mathbf{r}') \) confined within a volume \( V' \), the potential at a distant observation point \( \mathbf{r} \) can be expanded in powers of the ratio \( r'/r \). In this asymptotic regime, the mathematical boundary integrals governing the fields can be analyzed using advanced topological tools like the <strong>Generalized Stokes' Theorem</strong> to relate differential forms to boundary flux. The leading term in this expansion, which represents the total electric charge \( Q = \int \rho(\mathbf{r}') d^3r' \), recovers the standard mathematical relation of <strong>Coulomb's Law as a Static Limit</strong> for a point-like configuration. As the observation distance \( r \) increases, the higher-order spatial variations are systematically suppressed, allowing the complex fields of a structured charge distribution to be approximated as a superposition of simple multipole moments.</p>"""
        r"""<p>To formalize this asymptotic representation, we expand the inverse distance factor \( 1/|\mathbf{r} - \mathbf{r}'| \) using Legendre polynomials, which mathematically separates the coordinates of the observer from those of the source. This algebraic expansion yields the global electrostatic potential as a sum of discrete radial and angular moments, which serves as the primary engine for analyzing field symmetries. The resulting harmonic expansion of the electrostatic potential is formulated as"""
        r"""<div class="math-display" style="text-align: center; margin: 25px 0;">\[ \Phi(\mathbf{r}) = \frac{1}{4\pi\epsilon_0} \sum_{l=0}^\infty \frac{1}{r^{l+1}} \int (r')^l P_l(\cos\gamma) \rho(\mathbf{r}') d^3r' \]</div>"""
        r"""where \( \epsilon_0 \) represents the vacuum permittivity, \( r \) and \( r' \) are the radial distances of the observer and the source from the chosen origin, and \( P_l(\cos\gamma) \) denotes the Legendre polynomial of order \( l \) evaluated at the angle \( \gamma \) between the vectors \( \mathbf{r} \) and \( \mathbf{r}' \). The integration runs over the volume element \( d^3r' \) containing the charge distribution \( \rho(\mathbf{r}') \). Each term in the sum corresponds to a distinct multipole moment: the \( l=0 \) term represents the electric monopole, \( l=1 \) is the electric dipole, and \( l=2 \) corresponds to the electric quadrupole, each exhibiting a characteristic angular symmetry and radial decay.</p>"""
        r"""<p>This mathematical expansion of potentials is not restricted to electrostatic configurations, as an identical algebraic structure emerges when expanding the vector potential \( \mathbf{A}(\mathbf{r}) \) for localized steady currents \( \mathbf{J}(\mathbf{r}') \). When we formulate the magnetic vector potential, the equations of motion are governed by the vector Poisson relation, which is analyzed in <strong>The Differential Form of Magnetostatics</strong> to describe the curl of the magnetic field \( \mathbf{B} \). In magnetic media, these localized current loops form macroscopic magnetic dipoles that govern the behavior of <strong>Magnetism in Matter</strong>. The dynamic trajectories of charged particles moving through these multipole potential fields are determined by extremizing the action, a variational optimization governed by <strong>Hamilton's Principle</strong>. By analyzing how the Lagrangian depends on the multipole fields, physicists can predict the exact classical paths of particles without solving the full, complex field equations, showing the deep connection between potential symmetries and classical mechanics.</p>"""
        r"""<p>The physical elegance of this expansion is further illustrated by its immediate applicability to gravitational systems where mass density plays the role of charge density. Because Newtonian gravitation satisfies an inverse-square law mathematically equivalent to electrostatics, the gravitational potential \( \Phi_{\text{grav}}(\mathbf{r}) \) can be expanded in an identical Legendre series, illustrating how mass distributions like planets and stars generate fields that behave as point-mass fields at large distances. This structural parity proves that the expansion is a universal mathematical consequence of Laplace's equation in three dimensions, governing all <strong>Gravitational Fields as Conservative Systems</strong>. In these conservative gravitational configurations, the monopole moment corresponds to the total mass \( M \), while the vanishing of the gravitational dipole moment in the center-of-mass frame simplifies the orbital equations, allowing the quadrupole moment \( J_2 \) to represent the primary geometric correction due to rotation-induced oblatness.</p>"""
        r"""<p>The physical behavior of this harmonic representation undergoes a continuous mathematical reduction in the asymptotic limiting case where the distance from the source is formally taken to be infinitely large compared to the spatial extent of the charge distribution. In this asymptotic limit \( r \to \infty \), the higher-order multipole terms—including the dipole, quadrupole, and octupole moments—decay to zero exponentially faster than the monopole term, as their radial dependency scales as \( r^{-(l+1)} \) for all \( l \ge 1 \). The potential field \( \Phi(\mathbf{r}) \) simplifies directly to a simple, point-like spherically symmetric profile, recovering the standard Coulomb potential \( \Phi(r) \approx \frac{Q}{4\pi\epsilon_0 r} \). By demonstrating that the complex, multi-moment potential contracts smoothly to the monopole potential as the spatial coordinates are scaled outward, the theory establishes a mathematically rigorous and physically consistent bridge between structured, extended charge distributions and elementary point sources, validating the asymptotic consistency of the multipole expansion.</p>"""
    )

    # 3. Stable Equilibrium and Restoring Forces Prose
    stable_equilibrium_physics_html = (
        r"""<p>Perturbative analysis of a conservative physical system near a local minimum of its potential energy surface reveals that small displacements yield localized oscillatory behavior governed by a linear restoring force. When a particle of mass \( m \) is situated at a coordinate \( x_0 \) where the force \( F(x_0) = -\frac{dV}{dx}|_{x_0} \) vanishes, it is in a state of mechanical equilibrium. This stable local approximation is highly general, describing systems bound by electrostatic forces as well as subatomic interactions characterized by <strong>The Yukawa Potential</strong>. For a force to act as a restoring force that pulls the particle back toward the equilibrium position, the spatial field must be conservative, a constraint that requires the force field to have a vanishing curl under <strong>The Curl Operator (\(\nabla \times\))</strong>. Under these conservative physical conditions, the potential energy function \( V(x) \) can be expanded locally, allowing the dynamics of small perturbations to be formulated as</p>"""
        r"""<div class="math-display" style="text-align: center; margin: 25px 0;">\[ V(x) \approx V(x_0) + \frac{1}{2} k (x - x_0)^2 \]</div>"""
        r"""<p>where the effective spring constant is defined by the second spatial derivative of the potential, \( k = V''(x_0) \), which must be strictly positive to guarantee stability. This quadratic approximation reveals that the restoring force \( F(x) = -k(x-x_0) \) is linear, creating a harmonic potential well that traps the particle.</p>"""
        r"""<p>To derive the complete equations of motion for this perturbed oscillator without relying on ad-hoc Newtonian forces, we can construct the system's Lagrangian and apply variational principles. The difference between the kinetic energy \( T = \frac{1}{2} m \dot{x}^2 \) and the harmonic potential \( V(x) \) defines the Lagrangian \( L(x, \dot{x}) = T - V \), which is integrated over the time interval \( [t_1, t_2] \) to yield the <strong>Action Functional</strong> \( S[x] \). Under the principle of stationary action, the physical trajectory \( x(t) \) must extremize this action integral, which mathematically yields the Euler-Lagrange equations. In the harmonic regime, this variational extremization leads directly to the linear differential relation \( m \ddot{x} + k(x-x_0) = 0 \), which governs the stable sinusoidal oscillations with natural frequency \( \omega_0 = \sqrt{k/m} \). The phase space trajectory of this conservative system forms a closed ellipse \( \frac{p^2}{2m} + \frac{1}{2}k q^2 = E \), which represents the conservation of energy. By demonstrating that the harmonic equations emerge naturally from the action functional, the theory establishes a mathematically rigorous foundation for normal mode analysis in complex multi-component systems, allowing large lattices of coupled particles to be decomposed into independent harmonic coordinates.</p>"""
        r"""<p>Analyzing these stable oscillations in electrodynamic environments reveals a fundamental coupling between mechanics and field radiation. When a charged particle undergoes harmonic motion, its changing acceleration generates propagating electromagnetic waves, showing that <strong>Acceleration as the Source of Radiation</strong> acts as a dissipative mechanism that drains energy from the mechanical oscillator. To calculate the electromagnetic fields associated with this radiating charge, physicists solve Maxwell's relations under specific gauge constraints, such as the <strong>Coulomb Gauge (\( \nabla \cdot \mathbf{A} = 0 \))</strong>, where the scalar potential is determined instantaneously by the charge distribution while the vector potential \( \mathbf{A} \) propagates at the speed of light \( c \). These coupled differential field equations and their mechanical boundary conditions are solved using the unified methods of <strong>Universal Calculus</strong>, which provides the mathematical tools to analyze the transition from localized stable equilibria to radiating dynamical systems. This calculus demonstrates how the static restoring forces are continuously modified by the radiation reaction force \( \mathbf{F}_{\text{rad}} = \frac{\mu_0 q^2}{6\pi c} \ddot{\mathbf{v}} \), introducing a damping term \( \gamma \dot{x} \) that eventually halts the oscillation.</p>"""
        r"""<p>The physical behavior of this dynamical system undergoes a continuous mathematical reduction in the limiting case where the amplitude of the displacement \( \delta x = x - x_0 \) from the equilibrium point is formally taken to zero. In this infinitesimal limit \( \delta x \to 0 \), all higher-order anharmonic perturbations—including cubic and quartic terms in the Taylor expansion—decay to zero exponentially faster than the quadratic term, as their ratios scale as \( (\delta x)^n \) for \( n \ge 3 \). The physical potential \( V(x) \) reduces smoothly to a pure, symmetrical parabolic profile, and the equations of motion contract directly to the linear relations of the simple harmonic oscillator. Even in complex relativistic configurations, as the ratio of velocity to the speed of light \( v/c \to 0 \), the relativistic corrections to momentum contract to the classical mass, and the motion simplifies to standard Newtonian harmonic motion. By demonstrating that the complex, non-linear physical potential contracts smoothly to the symmetric harmonic approximation under these small-amplitude conditions, the theory establishes a mathematically consistent and physically robust link between arbitrary potential landscapes and the fundamental physics of harmonic oscillation.</p>"""
    )

    # Update payload
    payload["effective-potential-mechanics"]["content"] = effective_potential_mechanics_html
    payload["effective-potential-mechanics"]["identities"] = [
        {
            "id": "effective-potential-mechanics-identity-1-6d954933",
            "title": "Effective Potential for Central Force Motion",
            "equation": r"V_{\text{eff}}(r) = V(r) + \frac{L^2}{2 m r^2}",
            "description": "Formulates the effective potential for a particle of mass $m$ and angular momentum $L$ in a central potential $V(r)$, reducing the two-dimensional radial motion to an equivalent one-dimensional problem."
        }
    ]

    payload["harmonic-expansion-potential"]["content"] = harmonic_expansion_potential_html
    payload["harmonic-expansion-potential"]["identities"] = [
        {
            "id": "harmonic-expansion-potential-identity-1-be927e34",
            "title": "Multipole Expansion of the Electrostatic Potential",
            "equation": r"\Phi(\mathbf{r}) = \frac{1}{4\pi\epsilon_0} \sum_{l=0}^\infty \frac{1}{r^{l+1}} \int (r')^l P_l(\cos\gamma) \rho(\mathbf{r}') d^3r'",
            "description": "Formulates the multipole expansion of the electrostatic potential in terms of Legendre polynomials $P_l(\cos\gamma)$ and source charge density $\rho(\mathbf{r}')$, separating the potential into monopole, dipole, quadrupole, and higher-order moments."
        }
    ]

    payload["stable-equilibrium-physics"]["content"] = stable_equilibrium_physics_html
    payload["stable-equilibrium-physics"]["identities"] = [
        {
            "id": "stable-equilibrium-physics-identity-1-09cbacdf",
            "title": "Harmonic Approximation of Potential near Stable Equilibrium",
            "equation": r"V(x) \approx V(x_0) + \frac{1}{2} k (x - x_0)^2",
            "description": "Formulates the Taylor expansion of a physical potential $V(x)$ about a stable equilibrium point $x_0$, demonstrating that small perturbations are governed by a linear restoring force with effective spring constant $k = V''(x_0)$."
        }
    ]

    with open("subfiles/batch_payload.json", "w") as f:
        json.dump(payload, f, indent=4)

    print("POPULATION SUCCESS: Populated effective-potential-mechanics, harmonic-expansion-potential, stable-equilibrium-physics.")

if __name__ == "__main__":
    populate()
