import json

def populate():
    # Read the existing scaffold to preserve keys and standards
    with open("subfiles/batch_payload.json", "r") as f:
        payload = json.load(f)

    # 1. Spatial Rotations in 4D Spacetime (5 paragraphs)
    spatial_rotations_lorentz_html = (
        r"""<p>Symmetry operators representing spatial transformations in a four-dimensional manifold form a closed subgroup of the Lorentz group, mapping the coordinates of rotating reference frames. In the presence of strong gravitational fields, these rotational coordinates are coupled to the <strong>Gravitational Redshift</strong> \( z = \frac{\nu_0 - \nu}{\nu} \), which describes how the frequency of light is shifted as it escapes a gravitational well. The kinematic velocity along these rotating world-lines is characterized by the <strong>Definition of Four-Velocity</strong> \( U^\mu = \frac{dx^\mu}{d\tau} \), which satisfies the absolute metric constraint \( U^\mu U_\mu = -c^2 \) across all coordinate frames. By defining these spatial rotations as geometric transformations on the four-dimensional manifold, special relativity unifies spatial orientation and temporal flow, proving that physical observations are covariant under all spatial coordinate rotations. By conceptualizing the rotation operator through the generators of the Lie algebra \( \mathfrak{so}(3) \), physicists establish a direct correspondence between classical angular momentum and the Lorentz generators. This algebraic connection ensures that spatial rotations remain isotropic across all sectors of the manifold, preventing any directional asymmetry from disrupting the local conservation of momentum. Within this rotational framework, the angular coordinates are smoothly mapped across the pseudo-Riemannian metric, confirming that spatial orientation is a fundamental, observer-independent property of the underlying spacetime geometry.</p>"""
        r"""<p>To construct the formal variational foundation for these spatial rotations, physicists formulate the trajectories of particles using action integrals that are invariant under orthogonal coordinate transformations. This variational description is governed by <strong>Hamilton's Principle</strong>, which asserts that the physical trajectory of a body is the one that extremizes the action functional \( S = \int L dt \). Under spatial rotations, the Lagrangian \( L = \frac{1}{2}m\mathbf{v}^2 - V(\mathbf{r}) \) in static potentials remains completely invariant, leading to the conservation of angular momentum through Noether's theorem. By extending this variational principle to four dimensions, the action integral remains invariant under the full group of spatial rotations, guaranteeing that the equations of motion are covariant across all rotated reference frames. Under this relativistic formulation, the classical action functional is generalized to a coordinate-free representation where the particle's trajectory is parameterized by its proper time \( \tau \). The variation of the relativistic action \( S = \int d\tau \) with respect to the rotational coordinates yields the conserved angular momentum tensor \( J^{\mu\nu} \), which unifies classical angular momentum and the relativistic center-of-mass constants of motion. This variational symmetry guarantees that the physical path remains the straightest possible trajectory through the manifold, preserving the conserved quantities of the system.</p>"""
        r"""<p>The generalization of these spatial rotations to curved geometries requires incorporating gravitational curvature through covariant differentiation, which ensures that the tensor derivatives remain covariant. In this curved manifold, the directional derivatives are modified by the presence of the Christoffel <strong>Connection Coefficients</strong> \( \Gamma^\lambda_{\mu\nu} \), which represent the local gravitational field. The coordinate mapping between different rotated reference frames is governed by the <strong>Relativistic Coordinate Transformation</strong>, which relates the coordinates of events in different frames. The four-dimensional rotation matrix representing this spatial transformation around the z-axis is formulated as</p>"""
        r"""<div class="math-display" style="text-align: center; margin: 25px 0;">\[ R^\mu_{\ \nu} = \begin{pmatrix} 1 & 0 & 0 & 0 \\ 0 & \cos\theta & -\sin\theta & 0 \\ 0 & \sin\theta & \cos\theta & 0 \\ 0 & 0 & 0 & 1 \end{pmatrix} \]</div>"""
        r"""<p>where \( \theta \) represents the angle of rotation, and \( R^\mu_{\ \nu} \) denotes the rotation tensor. This matrix transformation preserves the spatial metric components while leaving the temporal components completely unaffected, demonstrating that spatial rotations form a distinct three-dimensional subgroup of the full four-dimensional Lorentz group.</p>"""
        r"""<p>Before the formulation of special relativity, spatial rotations were treated as independent symmetries of absolute space, completely decoupled from the flow of time. This classical description is analyzed in <strong>The Galilean Group</strong>, which governs the coordinate transformations of classical Newtonian mechanics under spatial rotations and uniform velocity boosts. Under this classical group, the spatial coordinates transform as \( \mathbf{r}' = \mathbf{R}\mathbf{r} \) while time \( t' = t \) remains completely invariant and absolute for all observers. This decoupling of space and time prevents any mixing of spatial and temporal coordinate components under boosts, isolating the spatial rotation group \( \text{SO}(3) \) from the Galilean boosts. The relativistic formulation resolves this isolation by embedding spatial rotations as a subgroup of the unified four-dimensional Lorentz group \( \text{SO}(1,3) \).</p>"""
        r"""<p>The physical behavior of this coordinate rotation mapping undergoes a continuous mathematical reduction in the classical limiting case where the relative boost velocities vanish completely, corresponding to a pure spatial rotation. In this static limit, the hyperbolic mixing terms associated with boosts vanish, and the four-dimensional Lorentz group contracts smoothly to the spatial rotation group \( \text{SO}(3) \). The four-dimensional rotation matrix is formulated as</p>"""
        r"""<div class="math-display" style="text-align: center; margin: 25px 0;">\[ R^\mu_{\ \nu} = \begin{pmatrix} 1 & 0 & 0 & 0 \\ 0 & \cos\theta & -\sin\theta & 0 \\ 0 & \sin\theta & \cos\theta & 0 \\ 0 & 0 & 0 & 1 \end{pmatrix} \]</div>"""
        r"""<p>where \( R^\mu_{\ \nu} \) is the coordinate rotation boost tensor. Substituting the limit where boost parameters are zero collapses the four-dimensional transformation directly to the classical three-dimensional rotation relations, \( \mathbf{r}' = \mathbf{R}\mathbf{r} \) and \( t' = t \). The complex relativistic coupling collapses smoothly to this classical spatial rotation limit. By demonstrating that the four-dimensional rotation reduces smoothly to the classical rotation equations as boosts are restricted, the theory validates the mathematical continuity and physical consistency of the coordinate description, proving that spatial rotations are a robust, physically consistent, and coordinate-invariant representation of spacetime.</p>"""
    )

    # 2. Physical Absolutes in a Relative Universe (4 paragraphs)
    physical_absolutes_invariance_html = (
        r"""<p>Geometric invariants in a four-dimensional pseudo-Riemannian manifold establish the physical absolutes that remain completely unchanged under all hyperbolic coordinate rotations, anchoring the laws of physics. While the coordinate readings of spatial distance and temporal duration vary between observers, as described by the coordinate mappings of <strong>The Lorentz Transformations</strong>, the spacetime interval remains invariant. This frame-dependent nature of measurements is exemplified by the <strong>Relativity of Simultaneity</strong>, which demonstrates that observers in relative motion disagree on the temporal sequence of distant events. To mathematically formalize these invariant symmetries, physicists utilize the algebraic framework of <strong>Minkowski Matrices and the Lorentz Group</strong>, which govern the orthogonal transformations that preserve the spacetime metric. By identifying these coordinate-independent parameters, relativity proves that the laws of physics are not relative, but are grounded in absolute geometric invariants, providing a robust foundation that is free from observer dependencies. By establishing these absolute geometric baselines, physicists can distinguish between coordinate-dependent appearances and observer-independent physical realities. This geometric distinction implies that physical parameters such as the rest mass \( m_0 \), the electronic charge \( e \), and the fine-structure constant \( \alpha \) are not relative quantities, but are absolute scalars that characterize the structure of the manifold. Within this invariant framework, the topological properties of the light cone remain invariant under all coordinate boosts, ensuring that the global causal structure is conserved.</p>"""
        r"""<p>The fundamental geometric engine that governs these absolute invariants is the flat spacetime metric, which determines the physical intervals and causal relations between all physical events. This flat spacetime metric is formulated as</p>"""
        r"""<div class="math-display" style="text-align: center; margin: 25px 0;">\[ \eta_{\mu\nu} = \begin{pmatrix} -1 & 0 & 0 & 0 \\ 0 & 1 & 0 & 0 \\ 0 & 0 & 1 & 0 \\ 0 & 0 & 0 & 1 \end{pmatrix} \]</div>"""
        r"""<p>where \( \eta_{\mu\nu} \) represents the metric tensor of flat spacetime with signature \( (-, +, +, +) \), which establishes the invariant interval \( ds^2 = \eta_{\mu\nu} dx^\mu dx^\nu \). This metric tensor acts as the absolute baseline of physical geometry, defining the light-cone structure that bounds the propagation of all physical information. By organization of the coordinate grid in accordance with this metric, the spatial and temporal coordinates mix dynamically under boosts, ensuring that the velocity-independent speed of light remains constant for all observers. This metric formulation guarantees that the physical laws governing electromagnetism and quantum mechanics are covariant, preserving the causal ordering of cause and effect.</p>"""
        r"""<p>The operational validity of these absolute geometric structures is revealed by the mechanical behavior of moving bodies, which must satisfy the requirements of frame-independent scaling. As a particle moves at high velocity, its spatial dimensions contract along its direction of motion in accordance with <strong>The Length Contraction Formula</strong> \( L = L_0 \sqrt{1 - v^2/c^2} \), representing a coordinate deformation that preserves the invariant spacetime interval. This kinematic behavior is a direct consequence of <strong>The Principle of Relativity</strong>, which asserts that the laws of physics are identical across all inertial reference frames. To establish the variational foundation for these dynamics, physicists reformulate the trajectories of classical bodies using action integrals governed by <strong>Hamilton's Principle</strong>, which states that the physical path taken by a system extremizes the action functional \( S = \int L dt \). Under this variational description, the Lagrangian \( L = -m_0 c \sqrt{-\eta_{\mu\nu} U^\mu U^\nu} \) is formulated directly from the invariant inner product of the velocity four-vector, linking analytical mechanics to the absolute geometry of the spacetime manifold. Within this relativistic formulation of analytical mechanics, the action functional \( S \) serves as the ultimate coordinate-invariant scalar, ensuring that the physical equations of motion are identical for all observers. The variation of this action with respect to the coordinates yields the covariant equations of motion, which describe how the particle moves through flat or curved manifolds without relying on a preferred reference frame. This variational formulation confirms that the physical trajectories of particles are determined by the absolute geometry of the spacetime manifold, preserving the conserved quantities of the system under all boosts.</p>"""
        r"""<p>The physical behavior of this coordinate-invariant metric relation undergoes a continuous mathematical reduction in the non-relativistic limiting case where the relative velocity is formally small compared to the speed of light \( c \), corresponding to the limit \( c \to \infty \). In this Newtonian limit, the unified four-dimensional manifold separates into independent absolute space and absolute time domains. The Minkowski spacetime metric is formulated as</p>"""
        r"""<div class="math-display" style="text-align: center; margin: 25px 0;">\[ \eta_{\mu\nu} = \begin{pmatrix} -1 & 0 & 0 & 0 \\ 0 & 1 & 0 & 0 \\ 0 & 0 & 1 & 0 \\ 0 & 0 & 0 & 1 \end{pmatrix} \]</div>"""
        r"""<p>where \( \eta_{\mu\nu} \) is the flat metric tensor. Substituting the limit \( c \to \infty \) into this covariant metric relation collapses the four-dimensional interval directly to the classical Galilean space interval \( dl^2 = dx^2 + dy^2 + dz^2 \) and the absolute temporal interval \( dt^2 \), which are independently conserved under all Galilean transformations. The complex relativistic metric coupling collapses smoothly to this classical representation, where spatial distance and absolute time are decoupled. By demonstrating that the relativistic metric reduces smoothly to these classical distance and time intervals as light speed is restricted, the theory validates the mathematical continuity and physical consistency of the geometric description across all velocity regimes, proving that the flat spacetime metric is a robust, physically consistent, and coordinate-invariant representation of the universe.</p>"""
    )

    # 3. Frequency and the Threshold Limit (4 paragraphs)
    threshold_frequency_photoelectric_html = (
        r"""<p>Quantum absorption in metallic lattices represents a threshold-governed process where electrons are ejected only when the incident radiation frequency exceeds a critical material-dependent limit, showing that energy is transferred in discrete packets. In quantum communication, this discrete absorption boundary sets the limit for the <strong>Maximum Possible Information</strong> \( I_{\max} = \log_2(1 + S/N) \) that can be transmitted per quantum channel, linking physical boundaries to information capacity. The wave-particle character of these interacting quantum entities was historically established by <strong>The Davisson-Germer Experiment</strong>, which verified the wave-like diffraction of electrons scattered by nickel crystals, confirming the de Broglie hypothesis. In quantum mechanics, the states of these bound electrons are mathematically represented by <strong>Square-Integrable Functions (\(L^2\))</strong>, which define the probability density amplitudes of the electron wave function in Hilbert space, ensuring that the physical probabilities sum to unity. By organizing these discrete transitions as quantum leaps between bound and free states, the theory guarantees that the ejection of photoelectrons is an instantaneous, single-photon event rather than a gradual classical wave accumulation, establishing a clean boundary between quantum behavior and classical mechanics.</p>"""
        r"""<p>To generalize this quantum framework to other physical systems, the mathematical representation of fields must remain independent of the underlying coordinate geometry. In quantum gravity and advanced gauge theories, this coordinate-invariant requirement is known as <strong>Background Independence</strong>, which asserts that the physical laws must be formulated without referencing a fixed classical metric, allowing the geometry of spacetime to emerge dynamically. Within this background-independent description, the quantum states are defined in terms of dynamic operators that evolve in accordance with the geometry of the manifold, mirroring how the electronic states of a metal are shaped by the periodic potential of the lattice. By coupling the quantum transitions to these dynamic geometries, physicists construct a coordinate-agnostic description of quantum interactions, proving that both microscopic absorption and macroscopic spacetime geometry emerge from the same fundamental quantum principles, establishing a deep symmetry between particle dynamics and gravity.</p>"""
        r"""<p>The dynamic relation that governs these quantum transitions is formulated in terms of energy conservation between the incident radiation quantum and the ejected charge carrier. The incoming light is treated as a stream of localized wave packets whose characteristics are determined by <strong>Photon Energy and Spectral Resolution</strong> \( E = h\nu \), which links the frequency of light directly to its discrete energy content, preventing the classical ultraviolet catastrophe. In quantum foundations, the statistical behavior of these photoelectrons is analyzed in <strong>The Ensemble Interpretation</strong>, which treats the quantum state as a description of a virtual ensemble of similarly prepared systems, avoiding the paradoxes of wavefunction collapse. The mathematical equation governing this threshold-limited kinetic energy is formulated as</p>"""
        r"""<div class="math-display" style="text-align: center; margin: 25px 0;">\[ K_{\max} = h\nu - \Phi \]</div>"""
        r"""<p>where \( K_{\max} \) represents the maximum kinetic energy of the emitted photoelectrons, \( h \) is Planck's constant, \( \nu \) is the frequency of the incident light, and \( \Phi \) denotes the work function or binding energy of the metal. This coordinate equation implies that if the frequency of the incident light is less than the threshold frequency \( \nu_0 = \Phi / h \), the kinetic energy of the ejected electrons is negative, which physically represents a forbidden state where no photoemission can occur, proving that the ejection is a quantized, threshold-limited process.</p>"""
        r"""<p>The physical behavior of this photoelectric relation undergoes a continuous mathematical reduction in the classical limiting case where Planck's constant \( h \) is formally taken to be zero, corresponding to the limit \( h \to 0 \). In this classical limit, the discrete photon structure of electromagnetic radiation vanishes completely, and the wave energy becomes a continuous function of the classical wave amplitude \( E \propto A^2 \). The photoelectric Einstein equation is formulated as</p>"""
        r"""<div class="math-display" style="text-align: center; margin: 25px 0;">\[ K_{\max} = h\nu - \Phi \]</div>"""
        r"""<p>where \( K_{\max} \) represents the kinetic energy of the emitted electrons. Substituting the limit \( h \to 0 \) into this quantum relation collapses the energy equation directly to the classical electrodynamics wave description, where the kinetic energy of the ejected charges depends entirely on the continuous intensity of the incident wave and no threshold frequency exists. The complex quantum emission relation collapses smoothly to this classical limit, demonstrating that quantum mechanics reduces smoothly to classical behavior in the macroscopic limit. By demonstrating that the quantum relation reduces smoothly to the classical wave equations as Planck's constant is restricted, the theory validates the mathematical continuity and physical consistency of the potential description across both quantum and classical regimes, proving that the threshold limit is a robust, physically consistent, and coordinate-invariant representation of quantum mechanics.</p>"""
    )

    # Update payload
    payload["spatial-rotations-lorentz"]["content"] = spatial_rotations_lorentz_html
    payload["spatial-rotations-lorentz"]["identities"] = [
        {
            "id": "spatial-rotations-lorentz-identity-1-6590414c",
            "title": "The 4D Lorentz Rotation Matrix",
            "equation": r"R^\mu_{\ \nu} = \begin{pmatrix} 1 & 0 & 0 & 0 \\ 0 & \cos\theta & -\sin\theta & 0 \\ 0 & \sin\theta & \cos\theta & 0 \\ 0 & 0 & 0 & 1 \end{pmatrix}",
            "description": "Formulates the 4D Lorentz rotation matrix representing a spatial rotation by angle θ around the z-axis."
        }
    ]

    payload["physical-absolutes-invariance"]["content"] = physical_absolutes_invariance_html
    payload["physical-absolutes-invariance"]["identities"] = [
        {
            "id": "physical-absolutes-invariance-identity-1-315dbaf7",
            "title": "The Minkowski Spacetime Metric",
            "equation": r"\eta_{\mu\nu} = \begin{pmatrix} -1 & 0 & 0 & 0 \\ 0 & 1 & 0 & 0 \\ 0 & 0 & 1 & 0 \\ 0 & 0 & 0 & 1 \end{pmatrix}",
            "description": "Formulates the flat Minkowski metric tensor in coordinate matrix form with signature (-, +, +, +)."
        }
    ]

    payload["threshold-frequency-photoelectric"]["content"] = threshold_frequency_photoelectric_html
    payload["threshold-frequency-photoelectric"]["identities"] = [
        {
            "id": "threshold-frequency-photoelectric-identity-1-47dcd85b",
            "title": "The Photoelectric Einstein Equation",
            "equation": r"K_{\max} = h\nu - \Phi",
            "description": "Formulates the maximum kinetic energy of emitted photoelectrons in terms of Planck's constant, frequency, and work function."
        }
    ]

    with open("subfiles/batch_payload.json", "w") as f:
        json.dump(payload, f, indent=4)

    print("POPULATION SUCCESS: Loaded all three GQS targets into subfiles/batch_payload.json.")

if __name__ == "__main__":
    populate()
