import json

def populate():
    # Read the existing scaffold to preserve keys and standards
    with open("subfiles/batch_payload.json", "r") as f:
        payload = json.load(f)

    # 1. The Time-Dependent Schrödinger Equation (TDSE) (6 paragraphs)
    time_dependent_schrodinger_equation_html = (
        r"""<p>State vector evolution in complex Hilbert space is fundamentally governed by a first-order differential equation in time that couples the temporal derivative of the wave function to the action of the Hamiltonian operator. In classical analytical mechanics, this coordinate reduction is modeled through <strong>Routhian Reduction and Conserved Momenta</strong>, where cyclic coordinates are eliminated to isolate the active degrees of freedom \( (q_i, p_i) \). Under the field-theoretic extension of these dynamics, the wave function \( \Psi(x, t) \) behaves as a classical scalar field whose local propagation satisfies the appropriate <strong>Field Equations</strong> derived from the system Lagrangian. By requiring that the evolution is unitary, the theory guarantees that the normalization of the state is preserved over time, preventing any loss or creation of probability density across the spatial coordinates. This dynamical framework ensures that the state vector \( |\Psi(t)\rangle \) remains a complete representation of the system at every instant, establishing a coordinate-free representation of quantum kinematics.</p>"""
        r"""<p>To generalize this temporal evolution to curved spacetime manifolds, the Hamiltonian operator must be formulated in a way that respects the local symmetries of the gravitational field. This curved-space generalization must satisfy the requirements of <strong>The Equivalence Principle</strong>, which asserts that the local effects of gravity are indistinguishable from those of a uniformly accelerating reference frame. Within this gravitational description, the inertial mass \( m_i \) and gravitational mass \( m_g \) are set identically equal, ensuring that the local quantum trajectories remain independent of the particle's mass. By coupling the Schrödinger equation to the metric tensor \( g_{\mu\nu} \), the theory provides a locally Minkowski description of quantum transport, proving that the flow of phase is an intrinsic property of the local spacetime geometry.</p>"""
        r"""<p>The extension of this wave description to relativistic regimes requires that the wave function's coordinates transform covariantly under the full Poincaré group. In superstring theory, this point-like description is replaced by <strong>Extended Objects</strong>, which represent one-dimensional strings whose internal vibrational modes generate the spectrum of elementary particles. Under this description, the wave vector \( p_\mu \) of the propagating string is coupled to the target space coordinates \( x^\mu \), defining a generalized wave equation in the string Hilbert space \( \mathcal{H}_{\text{string}} \). This stringy formulation ensures that the quantum states satisfy the high-energy ultraviolet bounds, preventing the point-like divergences of traditional quantum field theories.</p>"""
        r"""<p>The coupling of these wave equations to the gauge fields of the Standard Model determines the mass and charge assignments of the propagating leptons. In the neutrino sector, the introduction of <strong>The Right-Handed Neutrino</strong> \( \nu_R \) allows for the formulation of a sterile singlet state that does not participate in weak interactions but carries a heavy Majorana mass \( M_R \). Under this Majorana formulation, the mass Lagrangian \( \mathcal{L}_{\text{mass}} \) mixes the left-handed and right-handed fields, explaining the sub-electronvolt scale of active neutrinos via the seesaw mechanism. This mass-generation scheme ensures that the propagating neutrino wave packets satisfy the proper kinetic relations, protecting the conservation of lepton number from topological anomalies.</p>"""
        r"""<p>The dynamic observables representing the kinematic properties of these wave functions are represented by self-adjoint operators acting on the dense domains of the Hilbert space. The spatial distribution of the particle is resolved by <strong>The Position Operator (\(\hat{x}\))</strong>, which acts as a multiplicative operator on the wave function \( \psi(x, t) \), defining the localized coordinates of the carrier wave. The conjugate momentum is governed by the derivative operator \( \hat{p} = -i\hbar\frac{\partial}{\partial x} \), which satisfies the canonical commutation relation \( [\hat{x}, \hat{p}] = i\hbar \) across all coordinates. By defining these canonical operators, the theory guarantees that the position and momentum satisfy the Heisenberg uncertainty relation, establishing the quantum-mechanical limits of simultaneous measurements.</p>"""
        r"""<p>The physical behavior of this temporal wave equation undergoes a continuous mathematical reduction in the classical limiting case where Planck's constant \( \hbar \) is formally taken to be zero, corresponding to the limit \( \hbar \to 0 \). In this classical limit, the highly oscillatory wave function collapses to a classical state represented by a rapidly varying phase \( S(x, t) \), and the quantum trajectory collapses to the path of classical mechanics. The Time-Dependent Schrödinger Equation is formulated as"""
        r"""<div class="math-display" style="text-align: center; margin: 25px 0;">\[ i\hbar\frac{\partial}{\partial t}|\Psi(t)\rangle = \hat{H}|\Psi(t)\rangle \]</div>"""
        r"""where \( \Psi(t) \) is the state vector. Substituting the limit \( \hbar \to 0 \) into this quantum relation collapses the wave equation directly to the classical Hamilton-Jacobi equation, where the wave phase matches the classical action functional. The complex quantum relation collapses smoothly to this classical Hamilton-Jacobi limit, demonstrating that quantum wave dynamics reduce smoothly to classical particle paths in the macroscopic limit. By demonstrating that the quantum relation reduces smoothly to the classical trajectory equations as Planck's constant is restricted, the theory validates the mathematical continuity and physical consistency of the wave description across both quantum and classical regimes, proving that the TDSE is a robust, physically consistent, and coordinate-invariant representation of quantum evolution.</p>"""
    )

    # 2. The Time-Independent Schrödinger Equation (TISE) (5 paragraphs)
    time_independent_schrodinger_equation_html = (
        r"""<p>Separation of variables in quantum mechanical wave equations isolates the temporal phase factor from the spatial amplitude, transforming the partial differential wave equation into a static eigenvalue problem. In quantum foundations, this linear structure is protected by the <strong>Principle of Superposition</strong>, which asserts that any linear combination of eigenmodes \( |\psi_n\rangle \) with complex coefficients \( c_n \) represents a physically allowed state of the system. Under classical analytical mechanics, the geometric structure of the phase coordinates is modeled using <strong>Symplectic Geometry</strong>, where the closed differential two-form governs the phase space trajectories of classical systems with characteristic frequency \( \omega \). By requiring that the Hamiltonian operator is self-adjoint, the theory guarantees that the energy eigenvalues are strictly real, allowing the stationary states to represent stable configurations of the quantum system, establishing a coordinate-free representation of stationary wave kinematics.</p>"""
        r"""<p>To construct a formal variational foundation for these stationary states, the spatial amplitude functions are derived from action integrals that are invariant under all spatial translations. This variational formulation is governed by <strong>The Principle of Least Action</strong>, which states that the physical path taken by a system extremizes the action functional \( S = \int L dt \), satisfying \( \delta S = 0 \). Within this variational description, the stationary states represent the extremized configurations of the energy functional at a fixed total energy \( E_{\text{total}} \), ensuring that the spatial profiles are stable under local perturbations. By coupling these stationary amplitudes to this action principle, the theory provides a coordinate-free description of stationary configurations, proving that the allowed energy levels are fundamental geometric properties of the potential boundaries.</p>"""
        r"""<p>The dynamic stability of these stationary wave profiles under time evolution requires that the potential energy boundaries remain completely static. This variational stability is formulated using <strong>Hamilton's Principle</strong>, which asserts that the physical equations of motion are derived by extremizing the integral of the Lagrangian \( L = K - V \) over time. Under this variational framework, the static nature of the potential leads directly to <strong>Conservation Laws</strong>, where the conservation of energy is represented by a self-adjoint operator \( \hat{H} \) commuting with all conserved charges \( \hat{Q}_k \) such that \( [\hat{H}, \hat{Q}_k] = 0 \). By defining these conservation boundaries, the global topology of the potential determines the discrete energy spectrum, linking the macroscopic boundary conditions to the microscopic energy levels. This boundary-induced discretization implies that the particle cannot exchange energy continuously with its surroundings, establishing the discrete quantum nature of bound states.</p>"""
        r"""<p>The temporal behavior of these stationary configurations is resolved by applying the unitary operator that generates translations in time. This dynamic mapping is governed by the <strong>Time Evolution</strong> operator \( \hat{U}(t) = e^{-i\hat{H}t/\hbar} \), which acts on the spatial states to generate their temporal phase evolution. The Time-Independent Schrödinger Equation is formulated as"""
        r"""<div class="math-display" style="text-align: center; margin: 25px 0;">\[ \hat{H}|\psi\rangle = E|\psi\rangle \]</div>"""
        r"""where \( \hat{H} \) is the Hamiltonian operator, \( |\psi\rangle \) is the spatial state vector, and \( E \) represents the energy eigenvalue. This eigenvalue equation implies that the state vector remains physically invariant under time evolution, changing only by a global phase factor that does not alter any observable probability density. This stationary equivalence provides the load-bearing symmetry of quantum mechanics, showing that the energy eigenvalues are intrinsic, coordinate-invariant properties of the system that are completely independent of the choice of time coordinate.</p>"""
        r"""<p>The physical behavior of this stationary eigenvalue relation undergoes a continuous mathematical reduction in the classical limiting case where Planck's constant \( \hbar \) is formally taken to be zero, corresponding to the limit \( \hbar \to 0 \). In this classical limit, the discrete energy levels \( E_n \) merge into a continuous spectrum, and the quantum eigenvalue equation collapses to the classical conservation of energy. Substituting the limit \( \hbar \to 0 \) into this quantum relation collapses the TISE directly to the classical Hamilton-Jacobi wave relation, where the energy eigenvalues match the classical Hamiltonian function \( H(q, p) = E \). The complex quantum relation collapses smoothly to this classical limit, demonstrating that quantum stationary states reduce smoothly to classical orbits in the macroscopic limit. By demonstrating that the quantum relation reduces smoothly to the classical energy equations as Planck's constant is restricted, the theory validates the mathematical continuity and physical consistency of the wave description across both quantum and classical regimes, proving that the TISE is a robust, physically consistent, and coordinate-invariant representation of quantum mechanics.</p>"""
    )

    # 3. The Propagator (4 paragraphs)
    quantum_propagator_html = (
        r"""<p>Transition amplitudes mapping the spatial coordinates of a localized quantum state at an initial time to its final configuration define the integral kernel of the quantum propagator \( K(x, t; x_0, t_0) \), characterizing quantum transport. In the rigorous formulation of wave mechanics, these state vectors are elements of an <strong>Infinite-Dimensional Hilbert Space</strong> \( \mathcal{H} \), which provides the complete inner product space required to accommodate continuous position and momentum spectra. In canonical quantum gravity, the corresponding geometric transition amplitudes govern the evolution of spatial spin networks, where the quantum area of a surface is resolved by the <strong>Area Operator</strong> \( \hat{A}_S \) acting on the network edges. This spatial triangulation is formulated in <strong>Loop Quantum Gravity (LQG)</strong>, which replaces the smooth metric background with a network of discrete area and volume quanta. By expressing this transition as the matrix element \( \langle x | \hat{U}(t, t_0) | x_0 \rangle \), the theory establishes the green's function for the wave equation, showing that the propagator is an intrinsic, coordinate-invariant measure of quantum-mechanical causality.</p>"""
        r"""<p>To construct a formal variational foundation for this transition kernel, the propagator is analytically continued to imaginary time, establishing a deep mathematical link between quantum dynamics and statistical thermodynamics. Under this Wick rotation \( t \to -i\tau \), the quantum propagator maps directly to the partition function of a thermal ensemble, linking the speed of phase evolution to the physical <strong>Entropy</strong> of the system. Within this statistical description, the density matrix \( \rho \) determines the informational entropy \( S = -k_B \text{Tr}(\rho \ln \rho) \), which bounds the rate of physical decoherence and information loss. By coupling the quantum propagator to these thermodynamic properties, the theory provides a coordinate-free description of quantum dissipation, proving that the flow of probability is intimately linked to the thermodynamic arrow of time. This thermodynamic equivalence maps quantum fluctuations directly onto thermal distributions, showing that quantum statistical mechanics and classical statistical mechanics share a common geometric foundation. Consequently, the partition function acts as a generating functional for thermal expectations, bridging the gap between unitary quantum kinetics and macroscopic statistical laws.</p>"""
        r"""<p>The physical self-consistency of this transition amplitude requires that the propagation respects the causal boundaries imposed by the measurement process. When a measurement is performed on the propagating wave packet \( \psi(x, t) \), the continuous unitary evolution is interrupted by <strong>Wave Function Collapse</strong>, which projects the state vector onto a single eigenstate of the observable. The unitary preservation of the probability amplitudes during propagation is guaranteed by <strong>The Self-Adjoint Condition</strong> \( \hat{H}^\dagger = \hat{H} \) imposed on the Hamiltonian operator, ensuring that the eigenvalues are real. By defining this self-adjoint constraint, the global geometry of the Hilbert space ensures that the total probability integrated over all space remains constant, protecting the causal structure from probability leaks. This structural self-consistency ensures that the transition amplitudes are physically well-defined, preventing any instantaneous transmission of information across space-like separated intervals, which would violate the relativistic speed limits of flat spacetime. By enforcing these relativistic speed bounds on the propagator's support, quantum mechanics remains compatible with the local causal structure of Minkowski spacetime.</p>"""
        r"""<p>The physical behavior of this transition amplitude undergoes a continuous mathematical reduction in the classical limiting case where Planck's constant \( \hbar \) is formally taken to be zero, corresponding to the limit \( \hbar \to 0 \). In this classical limit, the infinite number of quantum paths interfere destructively, and the path integral collapses to the single deterministic trajectory that extremizes the classical action. The Propagator is formulated as"""
        r"""<div class="math-display" style="text-align: center; margin: 25px 0;">\[ K(x, t; x_0, t_0) = \int \mathcal{D}[x(t)] e^{i S[x(t)]/\hbar} \]</div>"""
        r"""where \( K(x, t; x_0, t_0) \) represents the propagator, and \( S[x(t)] \) is the action functional. Substituting the limit \( \hbar \to 0 \) into this path integral relation collapses the quantum propagator directly to the classical Hamilton's principle, where only the path satisfying the classical equations of motion survives. The complex quantum propagator collapses smoothly to this classical limit, demonstrating that quantum path integrals reduce smoothly to classical dynamics in the macroscopic limit. By demonstrating that the quantum relation reduces smoothly to the classical equations of motion as Planck's constant is restricted, the theory validates the mathematical continuity and physical consistency of the transition description across both quantum and classical regimes, proving that the propagator is a robust, physically consistent, and coordinate-invariant representation of quantum kinematics.</p>"""
    )

    # Update payload
    payload["time-dependent-schrodinger-equation"]["content"] = time_dependent_schrodinger_equation_html
    payload["time-dependent-schrodinger-equation"]["identities"] = [
        {
            "id": "time-dependent-schrodinger-equation-identity-1-1c6a704f",
            "title": "The Time-Dependent Schrödinger Equation",
            "equation": r"i\hbar\frac{\partial}{\partial t}|\Psi(t)\rangle = \hat{H}|\Psi(t)\rangle",
            "description": "Formulates the fundamental equation of motion in quantum mechanics, describing the temporal evolution of a state vector under the action of the Hamiltonian operator."
        }
    ]

    payload["time-independent-schrodinger-equation"]["content"] = time_independent_schrodinger_equation_html
    payload["time-independent-schrodinger-equation"]["identities"] = [
        {
            "id": "time-independent-schrodinger-equation-identity-1-aff33f30",
            "title": "The Time-Independent Schrödinger Equation",
            "equation": r"\hat{H}|\psi\rangle = E|\psi\rangle",
            "description": "Formulates the fundamental eigenvalue equation of quantum mechanics, describing the stationary states of a quantum system with discrete energy eigenvalues."
        }
    ]

    payload["quantum-propagator"]["content"] = quantum_propagator_html
    payload["quantum-propagator"]["identities"] = [
        {
            "id": "quantum-propagator-identity-1-ebfe1a77",
            "title": "The Quantum Path Integral Propagator",
            "equation": r"K(x, t; x_0, t_0) = \int \mathcal{D}[x(t)] e^{i S[x(t)]/\hbar}",
            "description": "Formulates the propagator as a sum over histories in the path integral formulation, where each path is weighted by the classical action."
        }
    ]

    with open("subfiles/batch_payload.json", "w") as f:
        json.dump(payload, f, indent=4)

    print("POPULATION SUCCESS: Loaded all three GQS targets into subfiles/batch_payload.json.")

if __name__ == "__main__":
    populate()
