import json

def populate():
    # Read the existing scaffold to preserve keys and standards
    with open("subfiles/batch_payload.json", "r") as f:
        payload = json.load(f)

    # 1. Stopping Potential and Retarding Fields (4 paragraphs)
    stopping_potential_physics_html = (
        r"""<p>Hyperbolic retarding potentials \( V(\mathbf{r}) \) applied to photoemissive surfaces establish a critical electrostatic barrier that halts the transport of ejected charge carriers, providing a direct measurement of photoelectron kinematics. To resolve the spectral and temporal characteristics of these carrier wave packets, physicists utilize integral transformations such as <strong>The Fourier Transform</strong> to map the localized wave functions \( \psi(\mathbf{r}) \) into momentum space, revealing the underlying distribution of momentum states. Under this mathematical formulation, the localized states of electrons bound in the metallic lattice can be modeled using the quantum harmonic approximation, as exemplified by the <strong>Harmonic Oscillator Quantum</strong> where energy eigenvalues \( E_n = \left(n + \frac{1}{2}\right)\hbar\omega \) are quantized in discrete rungs that represent the vibrational modes of the lattice. The operational observation of these retarding potentials is performed in a high-precision <strong>Measurement Apparatus</strong>, which consists of a vacuum tube with a variable voltage source that applies a decelerating field between the photoemissive cathode and the collecting anode. By varying this retarding field until the photocurrent \( I \) drops identically to zero, experimentalists can directly determine the maximum kinetic energy of the emitted photoelectrons, establishing that the photoelectron energy depends strictly on the radiation frequency rather than its classical intensity, which represents a crucial departure from classical electrodynamics.</p>"""
        r"""<p>The fundamental energy balance governing this retarding barrier is determined by the work done by the electrostatic field in halting the most energetic ejected electrons before they can reach the collecting anode. This energetic threshold is formulated as"""
        r"""<div class="math-display" style="text-align: center; margin: 25px 0;">\[ eV_0 = K_{\max} \]</div>"""
        r"""where \( e \) is the elementary charge of the electron, \( V_0 \) represents the stopping potential, and \( K_{\max} \) is the maximum kinetic energy of the photoelectrons immediately upon ejection from the metal surface. Under this energetic balance, the stopping potential acts as an absolute physical barrier that isolates the collector electrode from the arriving charge carriers, transforming the kinetic energy of the electrons entirely into electrostatic potential energy within the retarding field. By measuring this potential across a range of incident light frequencies, physicists confirmed the linear relation predicted by Einstein \( K_{\max} = h\nu - \Phi \), proving that electromagnetic radiation is quantized in discrete packets of energy. This energetic equivalence provides the load-bearing symmetry of the photoelectric effect, showing that the stopping potential is an intrinsic, coordinate-invariant measure of quantum kinematics that is completely independent of the wave amplitude \( A \) or light intensity.</p>"""
        r"""<p>In the presence of non-ideal metallic boundaries, the transport of these charge carriers is heavily influenced by quantum leakage through potential barriers, which alters the observed stopping potential and introduces anomalous leakage currents. This quantum leakage is characterized by <strong>Quantum Tunneling</strong>, which allows low-energy electrons to penetrate thin oxide layers or surface potential barriers \( U(\mathbf{r}) \) that would classically be forbidden, creating a measurable current \( I_{\text{tunnel}} \) even below the classical threshold. In quantum information theory, this discrete transport boundary determines the limit of <strong>Maximum Possible Information</strong> that can be extracted from a single quantum state, linking physical transport limits to information entropy and communication bounds. To generalize this quantum transport framework to arbitrary geometries without relying on a fixed coordinate system, the theory must satisfy the requirements of <strong>Background Independence</strong>, which asserts that physical laws are independent of any preferred background metric \( g_{\mu\nu} \). By formulating these retarding field equations in a background-independent manner, physicists ensure that the electrostatic potentials are derived from coordinate-covariant geometric relations rather than ad-hoc classical assumptions, preserving the topological symmetries of the field.</p>"""
        r"""<p>The physical behavior of this retarding energy balance undergoes a continuous mathematical reduction in the classical limiting case where Planck's constant \( h \) is formally taken to be zero, corresponding to the limit \( h \to 0 \). In this classical limit, the discrete photon structure of electromagnetic radiation vanishes completely, and the wave energy becomes a continuous function of the classical wave amplitude \( E \propto A^2 \), which represents the classical intensity. The stopping potential energy balance is formulated as"""
        r"""<div class="math-display" style="text-align: center; margin: 25px 0;">\[ eV_0 = K_{\max} \]</div>"""
        r"""where \( V_0 \) is the stopping potential. Substituting the limit \( h \to 0 \) into this quantum relation collapses the stopping potential equation directly to the classical electrodynamics wave description, where the photoelectron kinetic energy depends entirely on the continuous intensity of the incident wave and no threshold stopping potential exists. The complex quantum retarding relation collapses smoothly to this classical limit, demonstrating that quantum mechanics reduces smoothly to classical behavior in the macroscopic limit. By demonstrating that the quantum relation reduces smoothly to the classical wave equations as Planck's constant is restricted, the theory validates the mathematical continuity and physical consistency of the potential description across both quantum and classical regimes, proving that the stopping potential is a robust, physically consistent, and coordinate-invariant representation of quantum mechanics.</p>"""
    )

    # 2. Einstein's Photoelectric Equation (5 paragraphs)
    photoelectric_equation_einstein_html = (
        r"""<p>Energy quantization in electromagnetic interactions governs the discrete transfer of electromagnetic wave packets, equating the incident quantum energy \( E = h\nu \) of a photon to the sum of the metal work function \( \Phi \) and the maximum kinetic energy of the ejected electron. In quantum statistical mechanics, this discrete energy transfer is modeled in terms of localized energy packets, as exemplified by the <strong>Harmonic Oscillator Quantum</strong> where energy eigenvalues \( E_n = \left(n + \frac{1}{2}\right)h\nu \) are quantized in discrete rungs. The physical self-consistency of this quantized emission process is fundamentally protected by the <strong>Conservation of Probability</strong>, which ensures that the sum of all transition probabilities \( \sum P_i \) remains identically equal to unity throughout the interaction. The quantum photoelectric Einstein equation is formulated as"""
        r"""<div class="math-display" style="text-align: center; margin: 25px 0;">\[ h\nu = \Phi + K_{\max} \]</div>"""
        r"""where \( h \) is Planck's constant, \( \nu \) is the frequency of the incident radiation, \( \Phi \) represents the work function of the metal, and \( K_{\max} \) is the maximum kinetic energy of the emitted photoelectron. By organizing this energy exchange as a single, indivisible collision between a photon and a bound electron, the equation eliminates the classical time delay predicted by continuous wave theories, establishing quantum mechanics as the definitive framework for subatomic light-matter interactions.</p>"""
        r"""<p>To construct a formal variational foundation for this quantized interaction, the equations of motion are derived from action integrals \( S = \int L dt \) that are invariant under all spatial coordinate translations. In advanced quantum gravity and field theories, this coordinate-invariant requirement is generalized to satisfy <strong>Background Independence</strong>, which asserts that the physical laws must be formulated without referencing a fixed classical metric \( g_{\mu\nu} \), allowing the geometry of spacetime to emerge dynamically. Within this background-independent description, the quantum states of the lattice are represented by dynamic operators that adapt to the local geometry, mirroring how the work function is determined by the local potential \( V(\mathbf{r}) \) of the periodic lattice. By coupling this energy equation to these dynamic geometries, the theory provides a coordinate-free description of the photoelectric effect, proving that the energy transfer is a fundamental geometric property of the quantum vacuum rather than an ad-hoc classical assumption.</p>"""
        r"""<p>The spatial distribution of these bound electronic states within the metallic lattice is characterized by wave functions whose amplitudes determine the probability of finding an electron at any given coordinate \( \mathbf{x} \). This spatial probability is governed by the <strong>Probability Density in Quantum Mechanics</strong> \( \rho = |\psi|^2  \), which must be integrated over the volume of the metal to satisfy the normalization constraint \( \int \rho \, d^3x = 1 \). Near the metallic boundary, these bound states are modeled in terms of <strong>Standing Waves and Quantization</strong>, which arise from the boundary conditions imposed by the lattice edges, restricting the allowed energy states of the electrons. By defining these boundary conditions, the global topology of the metal determines the discrete work function \( \Phi \), linking the macroscopic structure of the material to the microscopic energy threshold required for photoemission.</p>"""
        r"""<p>The statistical interpretation of these quantized emissions is resolved by analyzing large ensembles of independent photoelectric events under identical experimental conditions. In quantum foundations, this statistical analysis is formulated in <strong>Frequentist Statistics in Quantum Mechanics</strong>, which defines the probability of photoelectron emission as the limiting relative frequency of ejections in an infinite sequence of identical trials \( N \to \infty \). Under this frequentist description, the wavefunction \( \psi \) does not represent the state of a single individual electron, but describes the statistical properties of a virtual ensemble of similarly prepared particles. This statistical formulation ensures that the observed photocurrent, which emerges from millions of discrete photoelectron ejections, satisfies the macroscopic averages predicted by the quantum probability density \( P(\mathbf{x}) \), protecting the theory from subjective interpretational anomalies.</p>"""
        r"""<p>The physical behavior of this quantized photoelectric relation undergoes a continuous mathematical reduction in the classical limiting case where Planck's constant \( h \) is formally taken to be zero, corresponding to the limit \( h \to 0 \). In this classical limit, the discrete photon structure of electromagnetic radiation vanishes completely, and the wave energy becomes a continuous function of the classical wave amplitude \( E \propto A^2 \), representing the classical intensity. The quantum photoelectric Einstein equation is formulated as"""
        r"""<div class="math-display" style="text-align: center; margin: 25px 0;">\[ h\nu = \Phi + K_{\max} \]</div>"""
        r"""where \( K_{\max} \) is the photoelectron kinetic energy. Substituting the limit \( h \to 0 \) into this quantum relation collapses the photoelectric equation directly to the classical electrodynamics wave description, where the kinetic energy of the ejected charges depends entirely on the continuous intensity of the incident wave and no threshold frequency exists. The complex quantum relation collapses smoothly to this classical limit, demonstrating that quantum mechanics reduces smoothly to classical behavior in the macroscopic limit. By demonstrating that the quantum relation reduces smoothly to the classical wave equations as Planck's constant is restricted, the theory validates the mathematical continuity and physical consistency of the potential description, proving that Einstein's photoelectric equation is a robust, physically consistent, and coordinate-invariant representation of quantum mechanics.</p>"""
    )

    # 3. Intensity and Photon Flux (5 paragraphs)
    light_intensity_quantum_html = (
        r"""<p>The electromagnetic power density delivered to a unit surface \( A_{\text{area}} \) is fundamentally governed by the photon flux, which represents the number of discrete energy quanta arriving per unit area per unit time. In quantum kinematics, the energy of each individual quantum is determined by the <strong>Angular Frequency (\(\omega\)) and Quantum Energy</strong> \( E = \hbar\omega \), which couples the wave-like frequency directly to its particle-like energy content. In quantum foundations, the physical interpretation of this discrete flux is analyzed in <strong>The Ensemble Interpretation</strong>, which asserts that the quantum state describes a virtual ensemble of similarly prepared photons rather than an individual wave packet. By organizing this energy transport as a stream of discrete quanta, the theory establishes a direct link between classical wave intensity and quantum particle flux \( \Phi_{\text{photon}} \), proving that the macroscopic power of a light beam is an emergent property of millions of independent quantum collisions.</p>"""
        r"""<p>To construct a formal variational foundation for this quantum flux relation, the transport of photons is modeled in terms of action integrals \( S = \int L \, d^4x  \) that remain invariant under all spatial coordinate translations. In quantum gravity and advanced gauge theories, this coordinate-invariant requirement is generalized to satisfy <strong>Background Independence</strong>, which asserts that physical laws are formulated without referencing a fixed classical metric \( g_{\mu\nu} \). Within this background-independent description, the photon flux is represented by dynamic operators \( \hat{J}^\mu \) that adapt to the geometry of the manifold, ensuring that the conservation of energy is satisfied locally without relying on a preferred coordinate grid. By coupling this flux relation to these dynamic geometries, the theory provides a coordinate-free description of electromagnetic intensity, proving that the power flow is an intrinsic property of the quantum vacuum.</p>"""
        r"""<p>The statistical distribution of these photons across the wave front is characterized by probability density amplitudes whose magnitudes determine the local intensity of the radiation field. This spatial probability is governed by <strong>The Born Interpretation and Quantum Probability</strong>, which asserts that the square of the wave function's amplitude represents the probability density \( \rho(\mathbf{x}) = |\psi(\mathbf{x})|^2 \) of finding a photon at any given coordinate. When analyzing these distributions in spectral devices, the resolution of the interference patterns is determined by the <strong>Photon Energy and Spectral Resolution</strong>, which limits the precision with which the frequency and position of the photons can be simultaneously resolved \( \Delta\nu \, \Delta t \ge 1 \). By coupling the Born probability density to these spectral limits, the theory guarantees that the observed interference patterns are statistical averages of independent photon ejections, protecting the causal structure of the system from quantum non-local violations.</p>"""
        r"""<p>The wave-particle character of these propagating photons is mathematically resolved by linking their momentum \( \mathbf{p} \) and energy \( E_{\text{photon}} \) to their wavelength and frequency, illustrating the connection between wave optics and quantum mechanics. This quantum-classical correspondence is governed by <strong>de Broglie's Hypothesis</strong> \( \lambda = h/p \), which extends the wave-particle duality of light to all massive particles, showing that both matter and radiation share the same fundamental dual nature. Under this description, the photon flux can be mapped as a sequence of wave fronts whose propagation is determined by the wave vector \( \mathbf{k} \), which lies exactly along the trajectory of the photons. This wave vector alignment ensures that the radiated energy flows strictly along the light cone, preventing any leakage of energy into spacelike regions and preserving the causal boundary of the field.</p>"""
        r"""<p>The physical behavior of this quantum flux relation undergoes a continuous mathematical reduction in the classical limiting case where the photon flux is extremely large and Planck's constant \( \hbar \) is formally taken to be zero, corresponding to the limit \( \hbar \to 0 \). In this classical limit, the discrete photon structure of electromagnetic radiation vanishes completely, and the wave energy becomes a continuous function of the classical wave amplitude \( E_0^2 \), representing the classical intensity. The quantum light intensity relation is formulated as"""
        r"""<div class="math-display" style="text-align: center; margin: 25px 0;">\[ I = N \hbar \omega \]</div>"""
        r"""where \( I \) represents the light intensity, \( N \) is the photon flux, \( \hbar \) is the reduced Planck's constant, and \( \omega \) is the angular frequency of the light. Substituting the limit \( \hbar \to 0 \) into this quantum relation collapses the intensity equation directly to the classical electrodynamics wave description, where the light intensity is determined by the continuous Poynting vector \( \mathbf{S} = \mathbf{E} \times \mathbf{H} \) and no discrete photon flux can be resolved. The complex quantum relation collapses smoothly to this classical limit. By demonstrating that the quantum relation reduces smoothly to the classical wave equations as Planck's constant is restricted, the theory validates the mathematical continuity and physical consistency of the potential description across both quantum and classical regimes, proving that the light intensity relation is a robust, physically consistent, and coordinate-invariant representation of electromagnetic power.</p>"""
    )

    # Update payload
    payload["stopping-potential-physics"]["content"] = stopping_potential_physics_html
    payload["stopping-potential-physics"]["identities"] = [
        {
            "id": "stopping-potential-physics-identity-1-40aea4c3",
            "title": "The Stopping Potential Energy Balance",
            "equation": r"eV_0 = K_{\max}",
            "description": "Defines the stopping potential as the potential difference required to halt the most energetic photoelectrons with maximum kinetic energy."
        }
    ]

    payload["photoelectric-equation-einstein"]["content"] = photoelectric_equation_einstein_html
    payload["photoelectric-equation-einstein"]["identities"] = [
        {
            "id": "photoelectric-equation-einstein-identity-1-3be3f842",
            "title": "The Quantum Photoelectric Einstein Equation",
            "equation": r"h\nu = \Phi + K_{\max}",
            "description": "Formulates Einstein's photoelectric equation, equating the incident photon energy to the sum of the metal work function and the maximum kinetic energy of the ejected photoelectron."
        }
    ]

    payload["light-intensity-quantum"]["content"] = light_intensity_quantum_html
    payload["light-intensity-quantum"]["identities"] = [
        {
            "id": "light-intensity-quantum-identity-1-dd5a0bfc",
            "title": "The Quantum Light Intensity Relation",
            "equation": r"I = N \hbar \omega",
            "description": "Formulates the relation for light intensity in terms of the photon flux, reduced Planck's constant, and angular frequency."
        }
    ]

    with open("subfiles/batch_payload.json", "w") as f:
        json.dump(payload, f, indent=4)

    print("POPULATION SUCCESS: Loaded all three GQS targets into subfiles/batch_payload.json.")

if __name__ == "__main__":
    populate()
