import json

def populate():
    # Read the existing scaffold to preserve keys and standards
    with open("subfiles/batch_payload.json", "r") as f:
        payload = json.load(f)

    # 1. The Electromagnetic Stress-Energy Tensor (5 paragraphs)
    electromagnetic_stress_energy_tensor_html = (
        r"""<p>Conservation of energy and momentum in electrodynamic systems is formalized through a symmetric, second-rank tensor \( T^{\mu\nu} \) that describes the flow and storage of electromagnetic field quantities across the spacetime manifold. This energy-flow tensor is closely related to the spatial gradients of the potentials, which must satisfy <strong>The Perpendicular Property of Fields and Potentials</strong> where the electric field \( \mathbf{E} \) is orthogonal to constant potential boundaries \( \Phi \). Integrating these localized energy fluxes over bounded volumes is governed by the principles of <strong>Field Integration and Path Independence</strong>, which guarantee that the total energy change depends solely on the boundary values of the fields. The resulting stress-energy tensor provides a complete, coordinate-invariant representation of the field's mechanical impact, mapping energy density, energy flux \( \mathbf{S} = \frac{1}{\mu_0} \mathbf{E} \times \mathbf{B} \), and momentum density into a single unified geometric object. This elegant representation is a cornerstone of classical electrodynamics, ensuring that the macroscopic energy-momentum transport remains continuous and conserved under all physical boundary constraints.</p>"""
        r"""<p>To integrate this stress-energy tensor into the relativistic dynamics of a charged particle, we analyze the local momentum exchange between the continuous fields and the localized charge carriers. This relativistic coupling is governed by the <strong>Energy-Momentum Relation</strong> \( E^2 = (pc)^2 + (m_0 c^2)^2 \), which defines the mechanical state of a particle with rest mass \( m_0 \) and momentum \( p \). The four-divergence of the stress-energy tensor, \( \partial_\nu T^{\mu\nu} = -F^{\mu\lambda} J_\lambda \), represents the local transfer of energy and momentum to the charged matter via the Lorentz force density. This covariant divergence relation guarantees that the total energy-momentum of the closed particle-field system remains perfectly conserved under all coordinate boosts, preserving the causal structure of special relativity.</p>"""
        r"""<p>The physical impact of these stress-energy fluxes is illustrated by the forces exerted on charges in electrostatic and magnetostatic configurations, where the fields act as momentum carriers. In static electric systems, the force exerted between point charges is governed by <strong>The Coulomb Force</strong> \( \mathbf{F}_C = \frac{q_1 q_2}{4\pi\varepsilon_0 r^2} \hat{\mathbf{r}} \), which is mathematically equivalent to the surface integral of the electrostatic Maxwell stress tensor. When charges move in inhomogeneous magnetic configurations, they experience spatial forces that are analyzed in <strong>Magnetic Mirroring and Particle Trapping</strong>, where the converging magnetic field lines exert a longitudinal force that reverses the particle's parallel velocity \( v_\parallel \). The stress-energy tensor naturally accommodates these transverse and longitudinal forces by representing them as spatial pressure and shear stresses, \( \sigma_{ij} = \varepsilon_0 E_i E_j + \frac{1}{\mu_0} B_i B_j - u_e \delta_{ij} \), within the material medium. These spatial stresses represent the physical tension of the field lines, showing how electrostatic fields pull charges together while magnetostatic fields push them sideways, providing a deep geometric explanation for classical electrostatic and magnetic forces.</p>"""
        r"""<p>In highly relativistic regimes where the source charges move at velocities close to the speed of light, the radiation fields exhibit a distinct forward-pointing deformation. This phenomenon is governed by <strong>Relativistic Beaming (The Searchlight Effect)</strong>, which concentrates the radiated power into a narrow cone of angular width \( \theta \approx 1/\gamma \) in the direction of velocity \( \mathbf{v} \). The covariant electromagnetic stress-energy tensor is formulated as</p>"""
        r"""<div class="math-display" style="text-align: center; margin: 25px 0;">\[ T^{\mu\nu} = \frac{1}{\mu_0} \left( F^{\mu\alpha} F^\nu_{\ \alpha} - \frac{1}{4} \eta^{\mu\nu} F^{\alpha\beta} F_{\alpha\beta} \right) \]</div>"""
        r"""<p>where \( F^{\mu\alpha} \) represents the antisymmetric electromagnetic field tensor, \( \eta^{\mu\nu} \) is the flat Minkowski metric, and \( \mu_0 \) is the permeability of free space. The forward-beaming effect is mathematically represented by the massive boost of the Poynting flux component \( T^{0i} \), illustrating how the stress-energy tensor deforms under high-speed transformations.</p>"""
        r"""<p>The physical behavior of this relativistic stress-energy tensor undergoes a continuous mathematical reduction in the static, non-relativistic limiting case where all time-varying magnetic fields are suppressed. In this electrostatic limit, the magnetic field vanishes, \( \mathbf{B} \to \mathbf{0} \), and the electromagnetic field tensor \( F^{\mu\nu} \) is determined solely by the static electric field \( \mathbf{E} \). The covariant stress-energy tensor \( T^{\mu\nu} \) simplifies directly to its spatial and temporal components, where the energy density component \( T^{00} \) contracts smoothly to the classical electrostatic energy density \( u_e = \frac{1}{2}\varepsilon_0 E^2 \). The complex four-dimensional tensor field contracts smoothly to this classical limit. By demonstrating that the relativistic stress-energy tensor reduces smoothly to the classical electrostatic energy density as dynamic magnetic contributions are suppressed, the theory validates the mathematical continuity and physical consistency of the tensor description across both relativistic and classical regimes, proving that the stress-energy tensor is a robust, causality-respecting formulation of electromagnetic energy conservation.</p>"""
    )

    # 2. The Covariant Inhomogeneous Maxwell Equation (6 paragraphs)
    covariant_inhomogeneous_equation_html = (
        r"""<p>Four-divergence relations of the electromagnetic field tensor \( F^{\mu\nu} \) are directly coupled to the charge and current distribution vectors \( J^\mu \), establishing a Lorentz-covariant foundation for all electrodynamic phenomena. In static systems, these dynamic field equations reduce directly to <strong>Irrotational Fields</strong> that have a vanishing curl and are derived from a scalar potential. The electrostatic force exerted between stationary charges in these conservative environments is governed by <strong>The Coulomb Force</strong> \( \mathbf{F} = \frac{q_1 q_2}{4\pi\varepsilon_0 r^2} \hat{\mathbf{r}} \), which serves as the physical limit for all electrostatic systems under free space permittivity \( \varepsilon_0 \). The covariant inhomogeneous equation unifies Gauss's law and Ampère's law into a single geometric statement, ensuring that the field equations remain invariant under all Lorentz transformations.</p>"""
        r"""<p>To derive this covariant source equation from first principles, physicists construct the action integral of the coupled field-particle system in the framework of analytical mechanics. This variational description is governed by the principle of <strong>Stationary Action</strong>, which asserts that the physical field configuration extremizes the action functional \( S[A_\mu] = \int \left( -\frac{1}{4\mu_0} F_{\alpha\beta} F^{\alpha\beta} - J^\mu A_\mu \right) d^4x \), where \( A_\mu \) is the four-potential and \( J^\mu \) is the four-current density. The variations of the action with respect to the four-potential \( A_\mu \) yield the Euler-Lagrange field equations, which reveal that the four-divergence of the field tensor must equal the four-current density. This variational coupling guarantees that the equations of motion are topologically robust, protecting the conservation of charge under all coordinate boosts.</p>"""
        r"""<p>The differential structure of these covariant field equations is heavily constrained by the matching conditions that govern the fields at physical interfaces. These boundary interactions are analyzed using <strong>Gauss's Law Boundary Conditions</strong> \( \left( \mathbf{D}_1 - \mathbf{D}_2 \right) \cdot \hat{\mathbf{n}} = \sigma_f \), which relate the normal component of the electric displacement field to the surface charge density under the unit normal vector \( \hat{\mathbf{n}} \). Under this covariant framework, these surface charges and currents are represented as a localized surface four-current \( K^\mu \), which determines the discontinuities in the electromagnetic field tensor \( F^{\mu\nu} \) at the boundary interface. This matching ensures that the global flux remains conserved, preventing unphysical source anomalies at the boundary.</p>"""
        r"""<p>To solve these covariant equations in dynamic environments, physicists introduce potential representations that uncouple the electric and magnetic fields. This potential representation defines the <strong>Potential Field</strong> \( A^\mu \), which combines the scalar potential \( \Phi \) and the vector potential \( \mathbf{A} \) into a single four-vector object. Enforcing the Lorenz gauge condition \( \partial_\mu A^\mu = 0 \) allows the covariant inhomogeneous wave equation to be written as \( \Box A^\mu = -\mu_0 J^\mu \), proving that the potentials propagate through space at the finite velocity of light \( c \). This wave propagation ensures that changes in the charge-current distribution propagate causally, maintaining the time-delay relations necessary for relativistic consistency.</p>"""
        r"""<p>The trajectories of the charged particles that act as the sources and targets of these potential waves are traced as continuous curves through the four-dimensional spacetime manifold. These curves are described as <strong>World Lines: The Trajectories of Reality</strong> \( z^\mu(\tau) \), which map the history of each particle as a function of its proper time \( \tau \). The four-current density \( J^\mu(x) \) is mathematically defined by integrating the particle's velocity along its world line, \( J^\mu(x) = \int q \frac{dz^\mu}{d\tau} \delta^4(x - z(\tau)) d\tau \). This direct link between the particle's history and the field source term guarantees that the covariant inhomogeneous wave equation remains self-consistent, ensuring that the fields respond causally to the physical trajectories of the charges.</p>"""
        r"""<p>The physical behavior of this covariant field equation undergoes a continuous mathematical reduction in the static limiting case where all physical quantities are independent of time, \( \partial_0 \to 0 \). In this static limit, the partial time derivatives vanish, and the electromagnetic field tensor \( F^{\mu\nu} \) simplifies directly to its spatial electric and magnetic components. The covariant inhomogeneous Maxwell equation is formulated as</p>"""
        r"""<div class="math-display" style="text-align: center; margin: 25px 0;">\[ \partial_\nu F^{\mu\nu} = \mu_0 J^\mu \]</div>"""
        r"""<p>where \( F^{\mu\nu} \) represents the antisymmetric electromagnetic field tensor, \( J^\mu \) is the four-current density, and \( \mu_0 \) is the permeability of free space. Substituting the static limit into this relation contracts the tensor equation directly to the electrostatic Gauss's law \( \nabla \cdot \mathbf{E} = \frac{\rho}{\varepsilon_0} \) and the magnetostatic Ampère's law \( \nabla \times \mathbf{B} = \mu_0 \mathbf{J} \). The complex four-dimensional tensor equation collapses smoothly to these classical limits. By demonstrating that the covariant relation contracts smoothly to these static equations as temporal variations are suppressed, the theory validates the mathematical continuity and physical consistency of the potential description across both relativistic and non-relativistic regimes, proving that the covariant inhomogeneous Maxwell equation is a robust, physically consistent representation of classical electrodynamics.</p>"""
    )

    # 3. The Electromagnetic Current (4 paragraphs)
    electromagnetic_current_physics_html = (
        r"""<p>Convection and conduction currents that transport electric charge through the spacetime manifold represent the source terms that couple the physical fields to particle dynamics in classical electrodynamics. In static systems, the magnetic field generated by these currents is governed by <strong>Magnetostatic Circulation</strong>, which relates the line integral of the magnetic field to the enclosed current. The propagation of the perturbations generated by these current sources is constrained by the speed of light, which represents <strong>The Velocity of Light (c)</strong> in vacuum. While the electric field is evaluated using <strong>The Integral Form of Gauss's Law</strong> to determine the total charge enclosed within a bounding surface \( d\mathbf{a} \), dynamic systems must combine the charge density and the current density into a single four-vector \( J^\mu \) to maintain covariance. This four-dimensional representation is essential because the individual charge density \( \rho \) and current density \( \mathbf{J} \) are not independent quantities, but mix under coordinate transformations, illustrating how space and time are physically bound in relativistic physics. Under a Lorentz boost, a pure static charge density in one frame is observed as a combination of charge and current in a moving frame, proving the absolute necessity of the covariant current description.</p>"""
        r"""<p>To derive this covariant current vector from first principles, physicists construct the coupled action integral in the framework of variational calculus. This description is governed by the principle of <strong>Least Action</strong>, which asserts that the physical trajectory of the particle-field system extremizes the action functional \( S = \int \left( L_{free} + L_{int} \right) dt \). The interaction Lagrangian is written as \( L_{int} = -q\Phi + q\mathbf{A} \cdot \mathbf{v} \), where \( \Phi \) and \( \mathbf{A} \) represent the scalar and vector potentials, and \( \mathbf{v} \) is the velocity of the particle. Expressing this interaction in terms of the four-vector potential \( A_\mu \) and the four-current \( J^\mu \) yields the interaction action \( S_{int} = -\int J^\mu A_\mu d^4x \), proving that the electromagnetic current acts as the mathematical link between particle kinematics and the variational dynamics of the gauge field. This variational coupling ensures that the equations of motion are topologically robust, protecting the conservation of charge under all coordinate boosts.</p>"""
        r"""<p>The differential structure of these current-potential interactions is formalized by the conservation laws that govern the divergence of the fields. While the field coordinates satisfy <strong>The Homogeneous Maxwell Equation</strong> \( \partial_\lambda F_{\mu\nu} + \partial_\mu F_{\nu\lambda} + \partial_\nu F_{\lambda\mu} = 0 \) to prevent magnetic monopoles, the inhomogeneous equations are driven by the four-current. The acceleration of these source currents in the presence of fields is governed by <strong>The Minkowski Force (K\(^\mu\))</strong> \( K^\mu = q F^{\mu\nu} u_\nu \), which describes the covariant momentum transfer between fields and particles. The electromagnetic four-current density is formulated as</p>"""
        r"""<div class="math-display" style="text-align: center; margin: 25px 0;">\[ J^\mu = \left( c\rho, \mathbf{J} \right) \]</div>"""
        r"""<p>where \( J^\mu \) represents the four-current density, \( c \) is the speed of light, \( \rho \) is the charge density, and \( \mathbf{J} \) denotes the three-current density vector. This four-dimensional representation guarantees that the local conservation of charge, \( \partial_\mu J^\mu = 0 \), is preserved under all coordinate transformations, ensuring that charge cannot be created or destroyed. The vanishing four-divergence \( \partial_\mu J^\mu = 0 \) represents a load-bearing symmetry of electrodynamics, enforcing that any change in the local charge density is perfectly balanced by the divergence of the current density. This charge conservation law is not a mere empirical observation, but is mathematically required by the gauge invariance of the electromagnetic coupling, linking the preservation of charge directly to the symmetries of the potential fields.</p>"""
        r"""<p>The physical behavior of this covariant four-current density undergoes a continuous mathematical reduction in the static limiting case where all source charges are at rest relative to the observer. In this static limit, the three-current density vector vanishes identically, \( \mathbf{J} \to \mathbf{0} \), eliminating any convection or conduction currents in the system. The electromagnetic four-current density is formulated as</p>"""
        r"""<div class="math-display" style="text-align: center; margin: 25px 0;">\[ J^\mu = \left( c\rho, \mathbf{J} \right) \]</div>"""
        r"""<p>where \( \rho \) represents the static charge density. Substituting the static limit \( \mathbf{J} = \mathbf{0} \) into this relation contracts the four-current density vector directly to a simple static charge four-vector \( J^\mu = (c\rho, \mathbf{0}) \). The complex dynamic four-current collapses smoothly to this static charge limit. By demonstrating that the four-current density contracts smoothly to this electrostatic representation as charge motions are suppressed, the theory validates the mathematical continuity and physical consistency of the covariant description, proving that the electromagnetic four-current is a robust, physically consistent, and coordinate-invariant representation of classical electrodynamics under all velocity regimes, protecting the energy conservation laws of classical physics.</p>"""
    )

    # Update payload
    payload["electromagnetic-stress-energy-tensor"]["content"] = electromagnetic_stress_energy_tensor_html
    payload["electromagnetic-stress-energy-tensor"]["identities"] = [
        {
            "id": "electromagnetic-stress-energy-tensor-identity-1-a7427134",
            "title": "The Covariant Electromagnetic Stress-Energy Tensor",
            "equation": r"T^{\mu\nu} = \frac{1}{\mu_0} \left( F^{\mu\alpha} F^\nu_{\ \alpha} - \frac{1}{4} \eta^{\mu\nu} F^{\alpha\beta} F_{\alpha\beta} \right)",
            "description": "Defines the symmetric, traceless electromagnetic stress-energy tensor $T^{\\mu\\nu}$ in terms of the electromagnetic field tensor $F^{\\mu\\nu}$ and the Minkowski metric $\\eta^{\\mu\\nu}$."
        }
    ]

    payload["covariant-inhomogeneous-equation"]["content"] = covariant_inhomogeneous_equation_html
    payload["covariant-inhomogeneous-equation"]["identities"] = [
        {
            "id": "covariant-inhomogeneous-equation-identity-1-df7e2d51",
            "title": "The Covariant Inhomogeneous Maxwell Equation",
            "equation": r"\partial_\nu F^{\mu\nu} = \mu_0 J^\mu",
            "description": "Formulates the inhomogeneous Maxwell equations in covariant form, relating the four-divergence of the antisymmetric electromagnetic field tensor $F^{\\mu\\nu}$ to the four-current density $J^\\mu$."
        }
    ]

    payload["electromagnetic-current-physics"]["content"] = electromagnetic_current_physics_html
    payload["electromagnetic-current-physics"]["identities"] = [
        {
            "id": "electromagnetic-current-physics-identity-1-3ea37a3a",
            "title": "The Electromagnetic Four-Current Density",
            "equation": r"J^\mu = \left( c\rho, \mathbf{J} \right)",
            "description": "Defines the electromagnetic four-current density $J^\\mu$ by combining the charge density $\\rho$ and the three-current density vector $\\mathbf{J}$ into a single Lorentz-covariant four-vector."
        }
    ]

    with open("subfiles/batch_payload.json", "w") as f:
        json.dump(payload, f, indent=4)

    print("POPULATION SUCCESS: Loaded all three GQS targets into subfiles/batch_payload.json.")

if __name__ == "__main__":
    populate()
