import json

def populate():
    # Read the existing scaffold to preserve keys and standards
    with open("subfiles/batch_payload.json", "r") as f:
        payload = json.load(f)

    # 1. The Cosmic Force of Acceleration (6 paragraphs)
    cosmic_force_acceleration_html = (
        r"""<p>Observations of distant Type Ia supernovae at cosmological distances reveal a cosmic expansion rate that is accelerating under the influence of a homogeneous dark energy field. On localized astrophysical scales, this cosmic expansion has no physical effect on stellar structures, which remain bound under self-gravity until they reach <strong>The Stability Limit of Degenerate Stars</strong> where degeneracy pressure fails. On the largest scales of the universe, however, this dark energy field drives a continuous, smooth <strong>Explosive Expansion</strong> of the spatial grid that determines the global geometry and ultimate thermal death of the cosmos. By parameterizing this acceleration in terms of the scale factor \( a(t) \) and its second time derivative \( \ddot{a} \), cosmologists modeled this phenomenon as a negative-pressure fluid governed by the cosmological constant \( \Lambda \) or a dynamical quintessence field with equation of state parameter \( w \).</p>"""
        r"""<p>To construct a formal variational foundation for this cosmic acceleration, the dark energy density is modeled as a vacuum energy tensor that remains invariant under all coordinate transformations. In special relativity, the four-momentum of high-energy particles must satisfy <strong>Energy-Momentum Relation</strong> \( p^\mu p_mu = -m^2 c^2 \), which limits the propagation of physical information to local inertial frames. In curved spacetime, the vacuum energy is represented by a stress-energy tensor \( T^{\mu\nu} = -\rho g_{\mu\nu} \) that acts as a source of gravity in the Einstein equations, where \( g_{\mu\nu} \) is the metric tensor and \( \rho \) is the vacuum density. By enforcing the covariant conservation law \( \nabla_\mu T^{\mu\nu} = 0 \), the theory guarantees that the vacuum energy density remains spatially uniform and temporally constant across the pseudo-Riemannian manifold, proving that the accelerating force is a fundamental geometric property of spacetime.</p>"""
        r"""<p>The observational detection of this accelerating expansion relies on measuring the luminosity distances of distant standard candles, which is completely independent of the local kinematic methods used in <strong>Statistical Parallax</strong> to determine stellar distances within the galaxy. By comparing the apparent magnitudes of Type Ia supernovae with their intrinsic luminosities, astronomers constructed a Hubble diagram that extends to high redshifts \( z \), mapping the expansion history of the universe over billions of years. This luminosity distance \( d_L \) is highly sensitive to the relative abundances of matter and dark energy, allowing cosmologists to constrain the density parameters \( \Omega_m \) and \( \Omega_\Lambda \) with high precision. This empirical alignment proved that the universe transitioned from a matter-dominated deceleration phase to a dark-energy-dominated acceleration phase at a redshift of approximately \( z \approx 0.6 \).</p>"""
        r"""<p>The microscopic physical mechanisms of the degenerate matter that forms these standard candles are governed by quantum mechanics, where the pressure inside white dwarfs is determined by electron degeneracy. In this degenerate regime, the electrons are packed into a dense Fermi gas where the <strong>Fermi Energy (\(E_F\))</strong> governs the maximum energy state of the particles and dictates the equations of state. This degenerate state is characterized by the Fermi momentum \( p_F \) and the number density \( n \), which provide the degenerate pressure \( P_{\text{deg}} \) required to support the white dwarf against gravitational collapse. When the star accretes matter and approaches the Chandrasekhar limit, a thermonuclear runaway is triggered, producing a highly standardized explosion whose light curve serves as the primary observational probe of the cosmological acceleration.</p>"""
        r"""<p>The calibration of these galactic distance indicators has been historically refined by space-based astrometry missions, such as <strong>The Hipparcos Mission</strong>, which measured the trigonometric parallaxes of nearby stars with unprecedented accuracy. By establishing a secure local anchor for the cosmic distance ladder, these astrometric measurements allowed astronomers to calibrate the Cepheid period-luminosity relation and reduce the systematic uncertainties in the Hubble constant \( H_0 \). The trigonometric parallax \( \pi \) and the geometric distance \( d = 1/\pi \) served as the first rung of the ladder, linking nearby stellar physics directly to the absolute luminosities \( L \) of more distant standard candles. This systematic calibration ensures that the derived cosmological parameters remain robust and free from local systematic biases, confirming the reality of the cosmic acceleration.</p>"""
        r"""<p>The physical behavior of this cosmic expansion relation undergoes a continuous mathematical reduction in the limiting case where the matter and radiation densities are formally taken to be zero, corresponding to the limit \( \rho \to 0 \) and \( P \to 0 \). In this vacuum-dominated limit, the gravitational attraction of baryonic and dark matter vanishes completely, and the spatial grid is governed solely by the cosmological constant. The Friedmann Acceleration Equation is formulated as</p>"""
        r"""<div class="math-display" style="text-align: center; margin: 25px 0;">\[ \frac{\ddot{a}}{a} = -\frac{4\pi G}{3} \left( \rho + \frac{3P}{c^2} \right) \]</div>"""
        r"""<p>where \( a(t) \) represents the scale factor, \( G \) is the gravitational constant, \( \rho \) is the energy density, and \( P \) is the pressure. Substituting the vacuum limit \( \rho \to 0 \) and \( P \to -\rho c^2 \) into this cosmological relation collapses the deceleration term directly to the de Sitter acceleration limit \( \ddot{a}/a = \frac{\Lambda c^2}{3} \), where the universe expands exponentially as \( a(t) \propto e^{Ht} \). The complex multi-component relation collapses smoothly to this de Sitter limit, demonstrating that cosmic acceleration reduces smoothly to empty vacuum expansion in the low-density limit, proving that the acceleration equation is a robust, physically consistent, and coordinate-invariant representation of cosmological dynamics.</p>"""
    )

    # 2. Recombination and the Last Scattering (6 paragraphs)
    recombination_cosmic_html = (
        r"""<p>Transition of the primordial plasma from an ionized state to a neutral gas occurred when the temperature of the expanding universe dropped below the binding energy of hydrogen, allowing protons and electrons to form stable atoms. Prior to this epoch, the cosmic background was a highly opaque, tightly coupled photon-baryon fluid that established the thermal homogeneity of <strong>The Isotropic Universe</strong> across all spatial directions. Unlike the localized, high-energy events of <strong>Thermonuclear Runaway</strong> that power classical novae in binary systems, this cosmic recombination was a smooth, global transition that occurred at a redshift of approximately \( z \approx 1100 \) when the temperature was around \( T \approx 3000 \text{ K} \). As the free electron fraction \( X_e \) dropped rapidly, the mean free path of photons became larger than the horizon size, causing the universe to become transparent and releasing the cosmic microwave background.</p>"""
        r"""<p>To construct a formal variational foundation for this decoupling, the transport of photons through the expanding plasma is modeled using the relativistic Boltzmann equation. In special relativity, the kinematics of these propagating photons must satisfy <strong>Energy-Momentum Relation</strong> \( p^\mu p_\mu = -m^2 c^2 \), which limits the propagation of light to null geodesics in the local frame. Within the expanding space, the four-momentum \( p_\mu \) of the photons is redshifted as they traverse the pseudo-Riemannian manifold, ensuring that their energy \( E = h\nu \) scales inversely with the scale factor of the metric tensor \( g_{\mu\nu} \). By coupling the photon Boltzmann equation to the electron-proton scattering rates, the theory provides a coordinate-free description of the last scattering surface, proving that the temperature fluctuations in the CMB are a direct historical record of the primordial acoustic oscillations.</p>"""
        r"""<p>The rate at which this recombination epoch proceeded was fundamentally governed by the expansion velocity of the cosmic grid, which is described by <strong>The Expansion Rate and Hubble Flow</strong>. As the scale factor \( a(t) \) of the universe expanded, the cooling of the plasma was determined by the time-dependent Hubble parameter \( H(t) \), which dictates the rate of temperature decrease. If the expansion rate had been significantly faster, the electrons and protons would have frozen out of equilibrium before combining, leaving a high residual ionization fraction that would have distorted the CMB spectrum. The smooth expansion flow ensured that the reaction rates could track the thermal evolution, allowing the recombination of hydrogen to proceed to completion over a short cosmic epoch \( \Delta t \).</p>"""
        r"""<p>In the modern cosmological epoch, the cosmic expansion has transitioned from a matter-dominated deceleration phase to a dark-energy-dominated acceleration phase, driven by <strong>The Cosmic Force of Acceleration</strong>. This accelerating expansion is parameterized by the cosmological constant \( \Lambda \) or a dark energy density \( \Omega_\Lambda \), which determines the ultimate deceleration parameter \( q_0 \equiv -a\ddot{a}/\dot{a}^2 \). Although dark energy dominates the energy budget of the modern universe, its influence was completely negligible during the recombination era, where the total density was dominated by dark matter and baryonic matter. This high-density matter ensured that the expansion rate was governed by the Einstein-de Sitter scaling, providing a stable, decelerating background that allowed the acoustic oscillations to imprint their characteristic scale on the CMB.</p>"""
        r"""<p>The quantum state of the degenerate electrons in the primordial plasma before recombination is modeled using statistical mechanics, where the electrons did not form a degenerate sea due to the high temperature. Unlike the high-density interior of white dwarfs where the electrons occupy <strong>The Fermi Sea</strong> and their degeneracy pressure supports the star, the primordial electrons existed as a classical, non-degenerate gas. Under these hot conditions, the electron energy states were distributed according to the Maxwell-Boltzmann distribution, where the Fermi energy \( E_F \) and Fermi momentum \( k_F \) played no role in the ionization balance, and the degeneracy pressure \( P_{\text{deg}} \) was completely absent. This non-degenerate state ensured that the ionization fraction depended solely on the thermal kinetic energy of the particles, allowing the recombination equations to be formulated using the standard chemical equilibrium relations.</p>"""
        r"""<p>The physical behavior of this ionization balance undergoes a continuous mathematical reduction in the high-temperature limiting case where the temperature is formally taken to be infinitely large, corresponding to the limit \( T \to \infty \). In this extreme hot limit, the thermal kinetic energy of the electrons is much larger than the ionization energy of hydrogen \( E_I = 13.6 \text{ eV} \), and the hydrogen atoms are completely dissociated. The Saha Ionization Equation for Recombination is formulated as the chemical equilibrium</p>"""
        r"""<div class="math-display" style="text-align: center; margin: 25px 0;">\[ \frac{X_e^2}{1 - X_e} = \frac{1}{\eta n_\gamma} \left( \frac{m_e k_B T}{2\pi \hbar^2} \right)^{3/2} e^{-\frac{E_I}{k_B T}} \]</div>"""
        r"""<p>where \( X_e \) represents the ionization fraction, \( \eta \) is the baryon-to-photon ratio, \( n_\gamma \) is the photon number density, \( m_e \) is the electron mass, \( k_B \) is the Boltzmann constant, and \( \hbar \) is the reduced Planck constant. Substituting the limit \( T \to \infty \) into this chemical relation collapses the ionization equation directly to the fully ionized limit \( X_e \to 1 \), where all hydrogen is ionized, and the neutral fraction vanishes. The complex chemical relation collapses smoothly to this plasma limit, demonstrating that recombination reduces smoothly to a fully ionized plasma in the hot limit, proving that the Saha equation is a robust, physically consistent, and coordinate-invariant representation of chemical thermodynamics.</p>"""
    )

    # 3. The Expansion Rate and Hubble Flow (5 paragraphs)
    expansion_rate_cosmic_html = (
        r"""<p>Recessional kinematics of distant galaxies relative to an observer are governed by a global velocity field that represents the continuous expansion of the spatial metric. On small astrophysical scales, this cosmic flow has no influence on nuclear fusion in stellar cores, which is instead governed by quantum tunneling through the Coulomb barrier via <strong>The Gamow Factor</strong>. On the largest scales of the universe, however, this spatial expansion has transitioned from a matter-dominated slowing phase to a dark-energy-dominated phase of <strong>Accelerated Expansion</strong> that stretches the coordinates of the cosmic web. By parameterizing this recessional motion in terms of the scale factor \( a(t) \) and its time derivative \( \dot{a} \), cosmologists define the expansion parameter \( H(t) \) that determines the recessional velocity \( v_c \) of galactic structures across space, establishing a dynamic relation that underpins all modern cosmological distance measurements.</p>"""
        r"""<p>To construct a formal variational foundation for this cosmic flow, the transport of mass-energy through the expanding metric is modeled using the stress-energy tensor of a perfect fluid. In special relativity, the four-momentum of the constituent particles must obey <strong>Energy-Momentum Relation</strong> \( p^\mu p_\mu = -m^2 c^2 \), which limits the local propagation of all physical information. In curved spacetime, the expansion of the metric tensor \( g_{\mu\nu} \) modifies the trajectories of these particles, forcing their four-momentum to adapt to the time-dependent metric coordinates. By coupling this expansion to the Einstein equations, the stress-energy tensor \( T^{\mu\nu} = (\rho + P/c^2) U^\mu U^\nu + P g_{\mu\nu} \) determines the acceleration or deceleration of the cosmic fluid, proving that the Hubble flow is a direct consequence of the global distribution of mass-energy.</p>"""
        r"""<p>The rigorous mathematical description of this cosmic expansion is formulated within the framework of <strong>General Relativity in Astrophysics and Cosmology</strong>, which relates the curvature of space directly to the expansion rate. By integrating the Friedmann equations over vast cosmological distances, cosmologists utilize the expansion history as a <strong>Precision Cosmological Tool</strong> to measure the density parameters and the age of the universe. The Hubble Parameter Relation is formulated as</p>"""
        r"""<div class="math-display" style="text-align: center; margin: 25px 0;">\[ H(t) = \frac{\dot{a}(t)}{a(t)} \]</div>"""
        r"""<p>where \( H(t) \) represents the Hubble parameter at any epoch, \( a(t) \) is the scale factor, and \( \dot{a}(t) \) is its first time derivative. This fundamental relation shows that the expansion rate is not a constant, but a dynamical parameter that depends on the total density \( \rho \) and gravitational constant \( G \), proving that the Hubble flow is a robust, physically consistent, and coordinate-invariant representation of spatial kinematics that links the local gravitational constant with the global properties of the spatial grid.</p>"""
        r"""<p>The physical behavior of this expansion parameter is highly sensitive to the dominant component of the cosmic fluid, which is modeled using a polytropic equation of state that relates pressure and density. Under different cosmological epochs, this relation is described by <strong>The Degeneracy Power Law</strong>, which parameterizes the scaling of pressure as a function of the scale factor. For a universe dominated by a fluid with equation of state parameter \( w \), the pressure satisfies \( P = w \rho c^2 \), which forces the scale factor to expand according to the power law \( a(t) \propto t^n \), where the exponent \( n \) determines the deceleration parameter. This scaling ensures that the expansion rate adapts to the thermodynamic properties of the cosmic fluid, linking quantum particle descriptions directly to the macroscopic expansion of space, and providing a powerful mathematical engine to model the cosmic cooling history.</p>"""
        r"""<p>The physical behavior of this expansion relation undergoes a continuous mathematical reduction in the static limiting case where the scale factor \( a(t) \) is formally taken to be constant, corresponding to the limit \( \dot{a} \to 0 \). In this static limit, the cosmological expansion of the spatial grid vanishes completely, and the galactic recessional velocities collapse smoothly to zero. Substituting the static limit \( \dot{a} \to 0 \) into this kinematic relation collapses the Hubble parameter directly to the static classical limit \( H(t) \to 0 \), where the spatial geometry is constant, and the coordinates are represented by a static Einstein universe or flat Minkowski space. The complex dynamic relation collapses smoothly to this static limit, demonstrating that cosmic expansion reduces smoothly to classical Galilean mechanics in the static limit, proving that the Hubble parameter relation is a robust, physically consistent, and coordinate-invariant representation of global kinematics across all stages of cosmic evolution.</p>"""
    )

    # Update payload
    payload["cosmic-force-acceleration"]["content"] = cosmic_force_acceleration_html
    payload["cosmic-force-acceleration"]["identities"] = [
        {
            "id": "cosmic-force-acceleration-identity-1-69edd2bc",
            "title": "The Friedmann Acceleration Equation",
            "equation": r"\frac{\ddot{a}}{a} = -\frac{4\pi G}{3} \left( \rho + \frac{3P}{c^2} \right)",
            "description": "Formulates the cosmological acceleration equation, showing that spatial expansion accelerates when the pressure satisfies the dark energy condition P < -1/3 rho c^2."
        }
    ]

    payload["recombination-cosmic"]["content"] = recombination_cosmic_html
    payload["recombination-cosmic"]["identities"] = [
        {
            "id": "recombination-cosmic-identity-1-f062f13f",
            "title": "The Saha Ionization Equation for Recombination",
            "equation": r"\frac{X_e^2}{1 - X_e} = \frac{1}{\eta n_\gamma} \left( \frac{m_e k_B T}{2\pi \hbar^2} \right)^{3/2} e^{-\frac{E_I}{k_B T}}",
            "description": "Formulates the Saha ionization equation describing the equilibrium ionization fraction of hydrogen during the recombination epoch of the early universe."
        }
    ]

    payload["expansion-rate-cosmic"]["content"] = expansion_rate_cosmic_html
    payload["expansion-rate-cosmic"]["identities"] = [
        {
            "id": "expansion-rate-cosmic-identity-1-961b60e6",
            "title": "The Hubble Parameter Relation",
            "equation": r"H(t) = \frac{\dot{a}(t)}{a(t)}",
            "description": "Formulates the Hubble parameter as the fractional rate of change of the scale factor, defining the expansion velocity of the cosmic flow at any cosmic epoch."
        }
    ]

    with open("subfiles/batch_payload.json", "w") as f:
        json.dump(payload, f, indent=4)

    print("POPULATION SUCCESS: Loaded all three GQS targets into subfiles/batch_payload.json.")

if __name__ == "__main__":
    populate()
