import json

def populate():
    # Read the existing scaffold to preserve keys and standards
    with open("subfiles/batch_payload.json", "r") as f:
        payload = json.load(f)

    # 1. Separable Hilbert Spaces (4 paragraphs)
    separable_space_html = (
        r"""<p>Countable orthonormal sequences \( \{\phi_n\}_{n=1}^\infty \) spanning an infinite-dimensional inner product space define the structural topology of a separable Hilbert space \( \mathcal{H} \), establishing the kinematic arena for quantum mechanics. To formulate coordinate-free dynamical trajectories, physicists define every first integral of motion as a <strong>Conserved Quantity</strong> \( Q \) represented by a self-adjoint operator commuting with the system Hamiltonian. In quantum gravity and canonical loop formulations, the spatial metric is represented in terms of a <strong>Densitized Triad</strong> \( E^a_i \) that facilitates the definition of coordinate-covariant connection fields on the spatial slice. Under gauge-invariant field configurations, these topological fields can host non-trivial topological defects, as exemplified by the existence of <strong>'t Hooft-Polyakov Monopoles</strong> arising from the spontaneous breaking of a grand unified gauge symmetry. By requiring the existence of a countable, dense subset of vectors, the theory guarantees that the space has a countable basis satisfying the orthonormality condition \( \langle \phi_i | \phi_j \rangle = \delta_{ij} \), allowing every physical state vector \( |\psi\rangle \) to be represented as a discrete linear combination of basis elements rather than an uncountable continuum of states.</p>"""
        r"""<p>The mathematical completeness of this countable basis ensures that the representation of state vectors is unique and physically well-behaved under unitary evolution. This completeness threshold is formulated as"""
        r"""<div class="math-display" style="text-align: center; margin: 25px 0;">\[ \sum_{n=1}^\infty |\phi_n\rangle\langle\phi_n| = I \]</div>"""
        r"""where \( I \) represents the identity operator on the space, and the projection operators \( |\phi_n\rangle\langle\phi_n| \) map any arbitrary state onto its coordinate component \( \langle \phi_n | \psi \rangle \) along the basis vector. Under this complete formulation, the Hilbert space is topologically isomorphic to the space of square-summable sequences \( \ell^2 \), ensuring that the physical description of wave functions remains invariant under change of basis. In special relativity, the causal geometry of physical fields is mapped onto flat spacetime using the <strong>The Minkowski Metric</strong> \( \eta_{\mu\nu} \) with signature \( (-, +, +, +) \), which establishes the invariant interval for wave propagation. By linking this complete sequence representation to the space of square-integrable functions \( \mathcal{L}^2(\mathbb{R}) \), the theory guarantees that the physical observables correspond to bounded self-adjoint operators, protecting the physical predictions from mathematical pathologies.</p>"""
        r"""<p>The countable nature of these bases ensures that the mathematical operators representing physical observables are defined on dense domains, avoiding the unbounded divergences of non-separable spaces. In analytical mechanics, this coordinate choice represents a modular gauge, mirroring the <strong>Coordinate Independence in Lagrangian Mechanics</strong> where the equations of motion are invariant under arbitrary coordinate transformations of the generalized coordinates \( q_i \) and velocities \( \dot{q}_i \). In the high-energy search for a unified description of all fundamental forces, a successful <strong>Theory of Everything</strong> must formulate its quantum gravitational states in a well-defined physical Hilbert space \( \mathcal{H}_{\text{phys}} \) that preserves this countable basis structure. By coupling the Lagrangian \( L(q, \dot{q}, t) \) to these countable spaces, physicists ensure that the path integrals converge to physically realizable probability amplitudes, protecting the topological properties of the underlying manifold from dimensional collapse. This mathematical convergence guarantees that the spectral decomposition of the Hamiltonian remains stable under infinite-dimensional perturbations \( V_{\text{pert}} \), establishing a mathematically consistent framework for analytical field dynamics.</p>"""
        r"""<p>The physical behavior of this countable basis representation undergoes a continuous mathematical reduction in the classical limiting case where the infinite dimensions contract to a finite-dimensional vector space \( N \), corresponding to the limit \( N \to \infty \) being restricted to a finite integer. In this finite-dimensional limit, the infinite-dimensional Hilbert space collapses smoothly to a standard Euclidean space \( \mathbb{R}^N \), where the completeness relation is a finite sum over \( N \) basis elements. The completeness relation of the orthonormal basis is formulated as"""
        r"""<div class="math-display" style="text-align: center; margin: 25px 0;">\[ \sum_{n=1}^\infty |\phi_n\rangle\langle\phi_n| = I \]</div>"""
        r"""where \( I \) is the identity operator. Substituting the limit of a finite basis size into this quantum relation collapses the infinite-dimensional sequence space \( \ell^2 \) directly to the classical matrix mechanics of finite dimensions, where all operators are bounded and the topological complexities of continuous spectra vanish. The complex infinite-dimensional representation collapses smoothly to this finite classical limit, demonstrating that infinite-dimensional Hilbert spaces reduce smoothly to classical vector behavior in the finite limit. By demonstrating that the countable completeness relation reduces smoothly to a finite matrix identity as the basis is restricted, the theory validates the mathematical continuity and physical consistency of the state representation across both quantum and classical limits, proving that the separable space is a robust, physically consistent, and coordinate-invariant representation of quantum systems.</p>"""
    )

    # 2. Geometric Bounds in Hilbert Space (5 paragraphs)
    geometric_bound_html = (
        r"""<p>Projective geometry in a complex vector space \( \mathcal{H} \) establishes fundamental metric limits that bound the inner product of state vectors, constraining the maximum possible overlap between physical states. In quantum gravity, these geometric limits govern the quantization of spatial geometry, where the connection variables are formulated using the <strong>Ashtekar-Barbero Connection</strong> \( A^a_i \) to describe the spatial curvature of the manifold. Under classical mechanics, these geometric constraints are modeled as symplectic forms, as exemplified by the mathematical framework of <strong>Hamiltonian Mechanics and Phase Space</strong> where physical trajectories are curves bounded by the geometry of the phase coordinates \( (q_i, p_i) \). The Cauchy-Schwarz inequality in Hilbert space is formulated as"""
        r"""<div class="math-display" style="text-align: center; margin: 25px 0;">\[ |\langle\psi|\phi\rangle|^2 \le \langle\psi|\psi\rangle\langle\phi|\phi\rangle \]</div>"""
        r"""where \( |\psi\rangle \) and \( |\phi\rangle \) are two arbitrary state vectors in the Hilbert space, and their inner product is bounded by their respective norms. By organizing these vector projections as geometric relations in a complex Hilbert space, this bound establishes the absolute upper limit for transition probabilities, proving that the probability of any quantum transition is topologically bounded by the metric structure of the space, which represents a crucial departure from classical infinite-dimensional linear systems.</p>"""
        r"""<p>To construct a formal variational foundation for these geometric bounds, the state trajectories are parameterized by paths in projective Hilbert space whose lengths determine the quantum speed limit. In relativistic quantum field theory, these trajectories must be covariant under all spacetime coordinate transformations, coupling the quantum speed to the relativistic <strong>The Energy-Momentum Relation</strong> \( E^2 = (pc)^2 + (m_0 c^2)^2 \), which limits the propagation velocity of all physical energy packets. Within this relativistic description, the energy \( E_{\text{photon}} \) and momentum \( p_{\text{momentum}} \) act as dynamic bounds on the rate of phase evolution, ensuring that the quantum state cannot evolve into an orthogonal state faster than the speed of light allows. By coupling the geometric bounds of Hilbert space to these relativistic limits, the theory provides a coordinate-free description of quantum evolution, proving that the speed of quantum information transfer is a fundamental geometric property of the quantum vacuum.</p>"""
        r"""<p>The global preservation of these geometric bounds under time evolution requires that the dynamical operators must be strictly unitary, protecting the probability amplitudes from unphysical growth. This coordinate-invariant requirement is generalized in quantum field theory to satisfy <strong>Manifest Covariance</strong>, which asserts that the physical laws must be formulated in terms of tensors that transform covariantly under the full Lorentz group, preserving the metric structure \( g_{\mu\nu} \). The dynamical conservation of these inner products is governed by <strong>Probability Conservation</strong>, which ensures that the unitary evolution operator \( U(t) \) satisfies the relation \( U^\dagger U = I \) at all times. By defining this unitary constraint, the global geometry of the Hilbert space ensures that the angle between any two state vectors remains invariant under time evolution, preventing any causal leakage or loss of coherence.</p>"""
        r"""<p>The algebraic decomposition of these geometric boundaries is resolved by analyzing the symmetry groups that govern the interactions of fundamental particles. In grand unified theories, this symmetric decomposition is formulated in <strong>The \(\bar{\mathbf{5}}\) Representation</strong> of the group \( \text{SU}(5) \), which groups three right-handed down quarks and two left-handed leptons into a single multiplet vector \( \psi_i \) in the unified Hilbert space \( \mathcal{H}_{\text{GUT}} \). Under this symmetric group, the inner products of the multiplet components must satisfy the global Cauchy-Schwarz bounds, protecting the unification scale from gauge anomalies and unphysical mixing. This group-theoretic formulation ensures that the observed transition rates, which arise from the decay of heavy bosons, satisfy the strict bounds predicted by the quantum probability density, protecting the causal structure of unified models.</p>"""
        r"""<p>The physical behavior of this geometric boundary undergoes a continuous mathematical reduction in the classical limiting case where the state vectors become collinear, corresponding to the limit \( \theta \to 0 \) where \( \theta \) is the angle between the vectors. In this collinear limit, the inequality collapses smoothly to a classical geometric equality, where the projection is a direct linear function of the vector lengths and \( \cos\theta = 1 \). The Cauchy-Schwarz inequality in Hilbert space is formulated as"""
        r"""<div class="math-display" style="text-align: center; margin: 25px 0;">\[ |\langle\psi|\phi\rangle|^2 \le \langle\psi|\psi\rangle\langle\phi|\phi\rangle \]</div>"""
        r"""where the inequality becomes a strict equality. Substituting the limit \( \theta \to 0 \) into this quantum relation collapses the geometric bound directly to the classical vector geometry, where the projected distance is simply the product of the vector magnitudes. The complex quantum bound collapses smoothly to this classical representation, demonstrating that quantum projection reduces smoothly to classical behavior in the collinear limit. By demonstrating that the quantum inequality reduces smoothly to the classical geometric equations as the angle is restricted, the theory validates the mathematical continuity and physical consistency of the potential description across both quantum and classical regimes, proving that the geometric bound is a robust, physically consistent, and coordinate-invariant representation of quantum mechanics.</p>"""
    )

    # 3. Complete Set of Commuting Observables (CSCO) (5 paragraphs)
    csco_html = (
        r"""<p>Simultaneous diagonalizability of self-adjoint operators \( \hat{A}_i \) in Hilbert space establishes the physical foundation for specifying the state of a quantum system without ambiguity. In classical analytical mechanics, this simultaneous specification corresponds to the elimination of cyclic coordinates, as described by <strong>Reduced Dynamics and the Routhian Formalism</strong> where the system coordinates \( (q_i, p_i) \) are reduced by utilizing conserved momenta. In quantum mechanics, these commuting operators have a deep <strong>Geometric Origin</strong> in the spatial symmetry group of the Hamiltonian \( \hat{H} \), where rotational and translational symmetries dictate the commutation relation \( [\hat{A}, \hat{B}] = 0 \). By organizing these observables as a complete commuting set, physicists can identify a unique basis of simultaneous eigenstates \( |a, b\rangle \) labeled by their eigenvalues, proving that the maximum possible information about a quantum state is obtained by measuring these commuting observables, establishing quantum mechanics as a complete and self-consistent framework for subatomic states.</p>"""
        r"""<p>To construct a formal variational foundation for these commuting observables, the simultaneous measurement states are derived from action integrals that are invariant under all symmetry transformations of the system. In advanced field theories, this variational description is governed by <strong>The Action Functional</strong> \( S[\phi] \), which asserts that the physical fields correspond to the paths that extremize the action, satisfying \( \delta S = 0 \) across the manifold. Within this variational description, the commuting operators \( \hat{A}_k \) correspond to the conserved Noether charges of the action, ensuring that the eigenvalues are constants of motion. By coupling these commuting observables to this action functional, the theory provides a coordinate-free description of quantum measurement, proving that the CSCO eigenvalues are intrinsic geometric invariants of the quantum fields rather than ad-hoc classical parameters.</p>"""
        r"""<p>The spatial decomposition of these simultaneous eigenstates is characterized by operators whose eigenvalues correspond to the conserved spatial quantities of the periodic system. For a rotating particle, this CSCO consists of the total <strong>Angular Momentum</strong> operator \( \hat{\mathbf{J}}^2 \) and its projection \( \hat{J}_z \) along a chosen axis, restricting the allowed quantum states to discrete integer or half-integer rungs. When analyzing entangled states in quantum foundations, the correlations between separated systems are modeled in terms of <strong>EPR Pairs</strong> \( \psi_{\text{EPR}} \), which represent maximally entangled states that challenge classical local realism. By defining these commuting operators, the global topology of the system determines the unique quantum numbers that label these entangled states, linking the macroscopic measurement setup to the microscopic quantum correlations.</p>"""
        r"""<p>The statistical interpretation of these simultaneous measurements is resolved by analyzing string-theoretic configurations where the boundary conditions restrict the allowed coordinates of propagating strings. In superstring theory, these boundary conditions are imposed by <strong>D-Branes</strong>, which represent dynamical surfaces where the endpoints of open strings are confined to slide, restricting the coordinates \( x^\mu \) of the string. Under this description, the commuting position operators \( \hat{X}^a \) along the brane form a CSCO that labels the physical states in the string Hilbert space \( \mathcal{H}_{\text{string}} \). This boundary formulation ensures that the string coordinates satisfy the macroscopic averages predicted by the quantum probability density, protecting the theory from causality violations.</p>"""
        r"""<p>The physical behavior of this complete commuting set undergoes a continuous mathematical reduction in the classical limiting case where Planck's constant \( \hbar \) is formally taken to be zero, corresponding to the limit \( \hbar \to 0 \). In this classical limit, the non-commuting quantum operators collapse to classical phase space coordinates, and the quantum commutator is replaced by the classical Poisson bracket \( \{A_i, A_j\} = 0 \), representing the classical independence. The simultaneous observability relation is formulated as"""
        r"""<div class="math-display" style="text-align: center; margin: 25px 0;">\[ [\hat{A}_i, \hat{A}_j] = 0 \]</div>"""
        r"""where \( \hat{A}_i \) are the commuting operators. Substituting the limit \( \hbar \to 0 \) into this quantum relation collapses the CSCO commutation relations directly to the classical Hamiltonian mechanics, where all physical variables are simultaneously measurable without uncertainty and the concept of state degeneracy vanishes. The complex quantum relation collapses smoothly to this classical limit, demonstrating that quantum measurement reduces smoothly to classical observation in the macroscopic limit. By demonstrating that the quantum relation reduces smoothly to the classical Poisson brackets as Planck's constant is restricted, the theory validates the mathematical continuity and physical consistency of the measurement description across both quantum and classical regimes, proving that the CSCO is a robust, physically consistent, and coordinate-invariant representation of quantum mechanics.</p>"""
    )

    # Update payload
    payload["separable-space"]["content"] = separable_space_html
    payload["separable-space"]["identities"] = [
        {
            "id": "separable-space-identity-1-c550056f",
            "title": "The Completeness Relation of Orthonormal Bases",
            "equation": r"\sum_{n=1}^\infty |\phi_n\rangle\langle\phi_n| = I",
            "description": "Formulates the resolution of identity in a separable Hilbert space using a countable orthonormal basis."
        }
    ]

    payload["geometric-bound"]["content"] = geometric_bound_html
    payload["geometric-bound"]["identities"] = [
        {
            "id": "geometric-bound-identity-1-947933ca",
            "title": "The Cauchy-Schwarz Inequality in Hilbert Space",
            "equation": r"|\langle\psi|\phi\rangle|^2 \le \langle\psi|\psi\rangle\langle\phi|\phi\rangle",
            "description": "Defines the fundamental geometric bound governing the inner product of state vectors in Hilbert space, representing the metric limit of vector projection."
        }
    ]

    payload["csco"]["content"] = csco_html
    payload["csco"]["identities"] = [
        {
            "id": "csco-identity-1-e4756fe2",
            "title": "The Simultaneous Observability Commutation Relation",
            "equation": r"[\hat{A}_i, \hat{A}_j] = 0",
            "description": "Formulates the required pairwise commutation relation for a set of operators to form a complete set of commuting observables, ensuring their simultaneous diagonalizability."
        }
    ]

    with open("subfiles/batch_payload.json", "w") as f:
        json.dump(payload, f, indent=4)

    print("POPULATION SUCCESS: Loaded all three GQS targets into subfiles/batch_payload.json.")

if __name__ == "__main__":
    populate()
