import json

def populate():
    # Read the existing scaffold to preserve keys and standards
    with open("subfiles/batch_payload.json", "r") as f:
        payload = json.load(f)

    # 1. The Lorentz Group as a Symmetry Group (5 paragraphs)
    symmetry_group_lorentz_html = (
        r"""<p>Symmetry operators in a four-dimensional pseudo-Riemannian manifold represent the foundational transformations that preserve the invariant spacetime interval, mapping coordinates between moving frames. This coordinate mapping is fundamentally constrained by the <strong>Relativity of Simultaneity</strong>, which establishes that observers in relative motion do not agree on the temporal ordering of distant events. In curved geometries, these local transformations must respect the physical constraints imposed by <strong>The Riemann Curvature Tensor</strong> \( R^\mu_{\ \nu\alpha\beta} \), which quantifies the local deviation of geodesics under gravitational influence. The coordinate transformation of event coordinates between independent reference frames is formulated as</p>"""
        r"""<div class="math-display" style="text-align: center; margin: 25px 0;">\[ x'^\mu = \Lambda^\mu_{\ \nu} x^\nu \]</div>"""
        r"""<p>where \( x^\nu = (ct, \mathbf{r}) \) represents the coordinate four-vector in the rest frame, and \( \Lambda^\mu_{\ \nu} \) denotes the Lorentz transformation tensor. By organizing these transformations as a continuous group, special relativity guarantees that the mathematical description of physical systems remains completely covariant, proving that physical observations are projections of a coordinate-independent spacetime geometry.</p>"""
        r"""<p>To construct the formal variational foundation for these coordinate transformations, physicists model the trajectories of classical and relativistic bodies in the language of analytical mechanics. This variational description is governed by <strong>Hamilton's Principle</strong>, which asserts that the physical trajectory of a body is the one that extremizes the action functional \( S = \int L dt \). Under the action of the symmetry group, the relativistic Lagrangian \( L = -m_0 c \sqrt{-g_{\mu\nu} U^\mu U^\nu} \) must remain completely invariant under all coordinate rotations and boosts, ensuring that the resulting equations of motion are covariant across all reference frames. The variations of this action with respect to these coordinates yield the geodesic equations of motion, confirming that the physical trajectory remains invariant under all coordinate boosts and rotations. This variational formulation demonstrates that physical conservation laws, such as the conservation of energy-momentum, are direct consequences of the underlying symmetries of the coordinate manifold.</p>"""
        r"""<p>The operational distinction between inertial and non-inertial coordinate frames is revealed by the presence of fictitious forces that arise from spatial rotation. In rotating classical frames, observers experience a velocity-dependent deviation known as the <strong>Coriolis Force</strong> \( \mathbf{F}_c = -2m(\boldsymbol{\omega}\times\mathbf{v}) \), which acts perpendicular to the direction of motion. In the framework of <strong>Special Relativity</strong>, these rotating frames generate non-trivial spatial metric deformations that restrict the rigidity of rotating bodies. By treating space and time as a unified manifold, the symmetry group transformations ensure that the causal structure remains invariant, preventing any non-causal propagation of signals. This coordinate representation ensures that all local dynamics, from electromagnetic field propagation to gravitational curvature interactions, can be tracked through continuous transformations, establishing a unified arena for all physical systems.</p>"""
        r"""<p>The geometric pathways followed by freely falling observers through this four-dimensional coordinate grid are determined by the extremization of proper time intervals between physical events. These physical pathways are mathematically modeled as <strong>Geodesics</strong>, along which a particle experiences zero proper acceleration. The coordinate equations governing these straightest paths are determined by the Christoffel connection coefficients, which represent the local gravitational field. By defining these boundary generators, the global topology of the manifold is constrained to be contractible, preventing any topological defects or multi-valued coordinate charts from disrupting the causal ordering. This geometric formulation demonstrates that even in the presence of gravitational curvature, the local coordinate boundaries of spacetime are strictly defined by the local symmetries.</p>"""
        r"""<p>The physical behavior of this coordinate symmetry group undergoes a continuous mathematical reduction in the non-relativistic limiting case where the relative velocity \( v \) is formally small compared to the speed of light \( c \), corresponding to the limit \( \beta \to 0 \). In this low-speed limit, the Lorentz factor \( \gamma = (1 - \beta^2)^{-1/2} \) contracts smoothly to unity \( \gamma \to 1 \), and the temporal mixing term \( \frac{vx}{c^2} \) vanishes completely. The coordinate Lorentz transformation is formulated as</p>"""
        r"""<div class="math-display" style="text-align: center; margin: 25px 0;">\[ x'^\mu = \Lambda^\mu_{\ \nu} x^\nu \]</div>"""
        r"""<p>where \( x'^\mu \) is the boosted coordinate four-vector. Under this low-speed restriction, the spatial components of the four-vector contract directly to the classical Galilean transformation relations, \( x' = x - vt \) and \( t' = t \). The complex relativistic boost matrix collapses smoothly to this classical representation, where spatial coordinates and time coordinates are completely decoupled. By demonstrating that the coordinate transformations reduce smoothly to the Galilean equations as boost velocities are restricted, the theory validates the mathematical continuity and physical consistency of the kinematic description across all velocity regimes, proving that the symmetry group is a robust, physically consistent, and coordinate-invariant representation of motion.</p>"""
    )

    # 2. The CPT Theorem and Lorentz Invariance (4 paragraphs)
    cpt_symmetry_theorem_html = (
        r"""<p>Quantum field theories formulated on a flat Minkowski spacetime are fundamentally constrained by CPT symmetry, which represents the combined operations of charge conjugation, parity inversion, and time reversal. In high-energy particle kinematics, this symmetry dictates that particles and antiparticles must possess identical masses and lifetimes, sharing the exact same <strong>Total Relativistic Energy</strong> \( E = \gamma m_0 c^2 \) at rest, which prevents any mass asymmetry in the vacuum. In gravitational physics, this symmetry is consistent with the weak equivalence principle, which requires that all test masses undergo <strong>Universal Free Fall</strong> in a gravitational field regardless of their internal quantum states, charge polarity, or spin configurations. Under a cosmological description, these inertial properties are analyzed in terms of <strong>Mach's Principle</strong>, which asserts that the local inertia of a body is determined by the global distribution of mass-energy in the universe. By organizing these coordinate translations as a continuous group of transformations, quantum field theory guarantees that CPT symmetry is a necessary consequence of local Lorentz invariance and microcausality, protecting the macroscopic causality of the universe from quantum non-local violations and providing a robust foundation for all particle interactions in the Standard Model.</p>"""
        r"""<p>To construct the formal variational foundation for these relativistic field symmetries, the lagrangians of quantum fields are written in a coordinate-invariant form that is extremized under all physical configurations across the entire manifold. This variational description is governed by <strong>Hamilton's Principle</strong>, which asserts that the physical trajectory of a body or field configuration extremizes the action functional \( S = \int L dt \). Under the CPT transformation, the field Lagrangian \( \mathcal{L} \) must remain completely invariant under all coordinate reflections and charge conjugations, ensuring that the resulting equations of motion are covariant and that the physical predictions remain identical for both matter and antimatter systems. The variations of this action with respect to these coordinates yield the conserved current equations, proving that CPT symmetry is a fundamental requirement for the self-consistency of the theory. This variational coupling demonstrates that the algebraic action of the symmetry is the fundamental driver of the system's dynamics, linking the abstract generators of the Lie algebra to the physical pathways of quantum and classical fields, preserving their symmetry properties under all coordinate shifts.</p>"""
        r"""<p>The geometric paths followed by classical bodies under these relativistic constraints represent the physical trajectories that extremize the temporal interval recorded by their moving clocks. In general relativity, these trajectories are characterized as paths of <strong>Maximum Proper Time</strong>, along which the proper acceleration experienced by a freely falling particle vanishes identically, representing the straightest possible path through the curved manifold. These physical pathways are mathematically modeled as <strong>Timelike Geodesics (\(ds^2 > 0\))</strong>, which describe how massive particles move through curved spacetime without proper acceleration. By defining these boundary generators, the global topology of the manifold is constrained to be contractible, preventing any topological defects or multi-valued coordinate charts from disrupting the causal ordering. This geometric formulation demonstrates that even in the presence of gravitational curvature, the local coordinate boundaries of spacetime are strictly defined by the light-cone structure, which isolates independent events and prevents superluminal signaling.</p>"""
        r"""<p>The physical behavior of this CPT field transformation undergoes a continuous mathematical reduction in the classical Newtonian limit where the speed of light \( c \) is formally taken to be infinite and quantum planck constant \( \hbar \) vanishes, corresponding to the limit \( c \to \infty \) and \( \hbar \to 0 \). In this classical limit, the quantum field operators reduce to classical spatial coordinates, and the complex CPT reflection collapses directly to classical spatial inversion \( \mathbf{r}' = -\mathbf{r} \) and classical time reversal \( t' = -t \). The CPT transformation operator is formulated as</p>"""
        r"""<div class="math-display" style="text-align: center; margin: 25px 0;">\[ \Theta \psi(x) \Theta^{-1} = \eta \gamma_5 \bar{\psi}^T(-x) \]</div>"""
        r"""<p>where \( \Theta \) represents the unitary CPT operator, \( \psi(x) \) is the Dirac field operator, \( \gamma_5 \) is the chiral Dirac matrix, and \( \bar{\psi}^T \) is the transposed conjugate field. Substituting the limits \( c \to \infty \) and \( \hbar \to 0 \) into this field transformation relation collapses the complex quantum spinor transformation directly to the classical coordinates reflection equations, \( \mathbf{x}' = -\mathbf{x} \) and \( t' = -t \). The complex relativistic spinor transformation collapses smoothly to this classical limit, demonstrating that Newtonian mechanics is an algebraic contraction of the more general Lorentzian symmetry. By demonstrating that the CPT field transformation reduces smoothly to these classical reflections as quantum and relativistic effects are suppressed, the theory validates the mathematical continuity and physical consistency of the coordinate description across all velocity regimes, proving that CPT symmetry is a robust, physically consistent, and coordinate-invariant representation of spacetime.</p>"""
    )

    # 3. The Invariant Inner Product (6 paragraphs)
    invariant_inner_product_spacetime_html = (
        r"""<p>Geometric projections in a four-dimensional pseudo-Riemannian manifold require an algebraic mapping that produces scalar quantities invariant under hyperbolic rotations. While coordinate measurements of spatial length are frame-dependent, as described by <strong>The Length Contraction Formula</strong> which details how spatial dimensions contract along their direction of motion, certain bilinear combinations of four-vectors remain absolutely constant. To preserve the covariance of physical laws under these transformations, the scalar products of coordinate four-vectors must satisfy <strong>Lorentz Invariance</strong>, ensuring that all observers measure the identical physical values. By organizing these scalar mappings as a continuous group of transformations, relativity unifies spatial projections and temporal durations, proving that the geometric structure of the manifold is determined by the underlying metric. This bilinear mapping ensures that the magnitude of physical quantities is preserved across all boosted coordinate frames, establishing a robust framework for all relativistic dynamics.</p>"""
        r"""<p>To construct the formal variational foundation for these coordinate-invariant scalar products, the equations of motion are derived from action integrals that are invariant under hyperbolic rotations across the entire manifold. This variational description is governed by <strong>Hamilton's Principle</strong>, which asserts that the physical trajectory of a body is the one that extremizes the action functional \( S = \int L dt \). Under the constraints of relativity, the Lagrangian \( L = -m_0 c \sqrt{-g_{\mu\nu} U^\mu U^\nu} \) is written as a function of the velocity four-vector and the metric tensor, ensuring that the Lagrangian is a Lorentz scalar derived from the inner product of the velocity components. The variations of this action with respect to the coordinates yield the covariant equations of motion, proving that conservation laws are direct consequences of the invariant symmetries. This variational coupling demonstrates that the fundamental dynamics of the system are driven by the extremization of coordinate-invariant scalars, linking the algebraic inner product to the physical pathways of moving bodies.</p>"""
        r"""<p>The generalization of this flat-space inner product to curved manifolds requires incorporating gravitational fields as localized coordinate symmetries that vary smoothly across the manifold. In this curved geometry, the directional derivatives of the four-vectors are modified by the presence of <strong>Connection Coefficients</strong> \( \Gamma^\lambda_{\mu\nu} \), which represent the local gravitational field and ensure that the derivative of the metric tensor vanishes identically. Under this covariant differentiation, the inner product of two vectors remains invariant under parallel transport, preserving the geometric relations between different points along the path. By coupling the inner product to these connection coefficients, physicists can construct the Riemann curvature tensor and define the geodesic equations of motion, which describe how massive particles move through curved spacetime. This local formulation guarantees that even in the presence of strong gravitational curvature, the inner product remains governed by the local metric tensor.</p>"""
        r"""<p>The causal structure of this four-dimensional coordinate manifold is fundamentally determined by the signs of the inner products of displacement four-vectors, which partition the manifold into causally distinct regions. This causal boundaries partition is governed by <strong>The Light Cone</strong>, which represents the null hypersurface where the inner product of the coordinate displacement four-vector with itself vanishes identically, \( ds^2 = 0 \). Two coordinate points are causally connected if their spatial separation is less than or equal to their temporal separation, corresponding to a timelike or null interval \( ds^2 \le 0 \), ensuring that no physical influence propagates faster than light. This geometric boundary separates the manifold into the causal future, the causal past, and the space-separated region, ensuring that the equations of motion satisfy the requirements of physical causality. The metric boundaries represent the absolute trajectories of light signals, defining a coordinate-independent partition of the spacetime manifold.</p>"""
        r"""<p>The coordinate transformations that preserve these inner products are represented as linear mappings that mix the temporal and spatial components of event four-vectors under velocity boosts. This coordinate mixing is analyzed in the <strong>Position Transformation</strong> equations of special relativity, which map the coordinate four-vector \( x^\mu = (ct, \mathbf{r}) \) in one inertial frame to \( x'^\mu \) in a boosted frame via the Lorentz boost tensor. Under these transformations, the spatial coordinates and coordinate time mix dynamically, illustrating how relativity unifies space and time into a single four-dimensional manifold. By organizing these position transformations as a continuous group of hyperbolic rotations, the boost matrix defines how physical fields and particle velocities are mapped between moving frames, preserving the invariant inner product of the coordinate differentials across all velocity regimes.</p>"""
        r"""<p>The physical behavior of this coordinate-invariant scalar mapping undergoes a continuous mathematical reduction in the non-relativistic limiting case where the speed of light \( c \) is formally taken to be infinite, corresponding to the limit \( c \to \infty \). In this Newtonian limit, the mixing between the temporal and spatial components of the inner product vanishes, and the causal cone opens up completely. The relativistic invariant inner product is formulated as</p>"""
        r"""<div class="math-display" style="text-align: center; margin: 25px 0;">\[ A^\mu B_\mu = \eta_{\mu\nu} A^\mu B^\nu \]</div>"""
        r"""<p>where \( A^\mu \) and \( B^\nu \) represent coordinate four-vectors, and \( \eta_{\mu\nu} \) is the flat Minkowski metric. Substituting the limit \( c \to \infty \) into this covariant metric relation collapses the four-dimensional inner product directly to the classical spatial inner product \( \mathbf{A} \cdot \mathbf{B} = A^x B^x + A^y B^y + A^z B^z \), while the temporal components decouple into absolute independent coordinates. The complex relativistic metric coupling collapses smoothly to this classical representation, where spatial inner products and temporal intervals are independently conserved. By demonstrating that the relativistic inner product reduces smoothly to the spatial Euclidean product as light speed is restricted, the theory validates the mathematical continuity and physical consistency of the kinematic description across all velocity regimes, proving that the inner product is a robust, physically consistent, and coordinate-invariant representation of spacetime.</p>"""
    )

    # Update payload
    payload["symmetry-group-lorentz"]["content"] = symmetry_group_lorentz_html
    payload["symmetry-group-lorentz"]["identities"] = [
        {
            "id": "symmetry-group-lorentz-identity-1-5ac1ddc7",
            "title": "The Lorentz Transformation of Spacetime Coordinates",
            "equation": r"x'^\mu = \Lambda^\mu_{\ \nu} x^\nu",
            "description": "Defines the Lorentz group transformations mapping event coordinates in one frame to another via the boost and rotation tensor matrix."
        }
    ]

    payload["cpt-symmetry-theorem"]["content"] = cpt_symmetry_theorem_html
    payload["cpt-symmetry-theorem"]["identities"] = [
        {
            "id": "cpt-symmetry-theorem-identity-1-0a866f11",
            "title": "The CPT Transformation Operator",
            "equation": r"\Theta \psi(x) \Theta^{-1} = \eta \gamma_5 \bar{\psi}^T(-x)",
            "description": "Defines the CPT transformation operator Θ acting on a Dirac field operator ψ(x), combining parity, charge, and time reversal symmetries in quantum field theory."
        }
    ]

    payload["invariant-inner-product-spacetime"]["content"] = invariant_inner_product_spacetime_html
    payload["invariant-inner-product-spacetime"]["identities"] = [
        {
            "id": "invariant-inner-product-spacetime-identity-1-db13bbb4",
            "title": "The Relativistic Invariant Inner Product",
            "equation": r"A^\mu B_\mu = \eta_{\mu\nu} A^\mu B^\nu",
            "description": "Defines the relativistic invariant inner product of two four-vectors A and B using the metric tensor."
        }
    ]

    with open("subfiles/batch_payload.json", "w") as f:
        json.dump(payload, f, indent=4)

    print("POPULATION SUCCESS: Loaded all three GQS targets into subfiles/batch_payload.json.")

if __name__ == "__main__":
    populate()
