import json

def populate():
    # Read the existing scaffold to preserve keys and standards
    with open("subfiles/batch_payload.json", "r") as f:
        payload = json.load(f)

    # 1. Taylor Expansion and the Harmonic Approximation Prose
    # Note: Use raw triple double quotes (r"""...""") and exactly two backslashes for MathJax delimiters
    taylor_expansion_mechanics_html = (
        r"""<p>Local approximation of a continuous, differentiable potential energy landscape in classical and quantum mechanics is mathematically achieved by expanding the function in an infinite power series about an equilibrium point. When a physical system experiences a potential energy \( V(x) \), its behavior near a local minimum \( x_0 \) governs the stability of small perturbations. In electrodynamic configurations, when a charged particle undergoes harmonic oscillations derived from this series, its total radiated power is governed by <strong>The Larmor Formula</strong>, which links the particle's acceleration \( \mathbf{a} \) to the emission of electromagnetic energy. In magnetostatic environments, localized steady currents generate vector potentials whose spatial characteristics are analyzed in <strong>The Differential Form of Magnetostatics</strong>, where series expansions serve as a direct mathematical tool to solve for the field strength. By representing the potential function as a power series, the complex forces acting on the particle can be decomposed into linear and non-linear components, simplifying the dynamical analysis near equilibrium.</p>"""
        r"""<p>To analyze the mechanical behavior near these potential minima, we utilize the coordinate transformations of classical kinematics to map the force fields onto flat manifolds. In the general relativistic description of gravitation, the local flatness of a pseudo-Riemannian spacetime manifold is conceptually analogous to this local quadratic approximation of a potential curve, a core mathematical feature that underpins the <strong>Principle of Equivalence</strong>. This principle establishes that a local non-gravitational coordinate frame is physically indistinguishable from a flat Minkowski space \( \eta_{\mu\nu} \) for any localized free-falling observer. Just as the general relativistic metric tensor \( g_{\mu\nu} \) contracts to the flat metric \( \eta_{\mu\nu} \) in a local neighborhood, any smooth physical potential \( V(x) \) can be treated as a flat, uniform potential up to first order, allowing the local dynamics of complex forces to be approximated by simple, uniform acceleration fields.</p>"""
        r"""<p>The mathematical representation of this localized power series is formalized by evaluating the successive derivatives of the potential function at the expansion coordinate, yielding a rigorous algebraic series that governs the potential profile. This power series expansion of the physical potential is formulated as</p>"""
        r"""<div class="math-display" style="text-align: center; margin: 25px 0;">\[ V(x) = V(x_0) + V'(x_0)(x-x_0) + \frac{1}{2}V''(x_0)(x-x_0)^2 + \mathcal{O}((x-x_0)^3) \]</div>"""
        r"""<p>where \( x_0 \) denotes the equilibrium position, \( V'(x_0) \) is the first derivative which vanishes identically at any local extremum, and \( V''(x_0) \) represents the potential curvature that defines the restoring spring constant \( k \). The higher-order terms are consolidated into the remainder term \( \mathcal{O}((x-x_0)^3) \). In time-varying electrodynamic systems, an oscillating magnetic flux through a circuit generates a localized electric field, producing a <strong>Transformer EMF</strong> that can be analyzed using these harmonic potential approximations. The spatial boundary contours of these induced fields are integrated over closed loops using <strong>Stokes' Theorem</strong>, which relates the surface integral of the magnetic curl \( \nabla \times \mathbf{E} \) to the line integral of the electric potential.</p>"""
        r"""<p>Evaluating this series expansion beyond the quadratic order reveals how higher-order perturbations like cubic and quartic terms introduce non-linearities into the equations of motion. For large coordinate displacements \( \delta x = x - x_0 \), these anharmonic terms distort the symmetric potential well, causing the oscillation frequency to run as a function of the energy \( E \). In highly sensitive electrostatic trapping systems, this potential distortion must be corrected by applying external, compensatory voltages to achieve <strong>Potential Compensation</strong>, ensuring that the trapping potential remains perfectly parabolic. This compensation technique is essential for precision experiments in quantum optics, where minor deviations from the quadratic potential would introduce unphysical couplings between the particle's motion and the background field fluctuations, destroying the coherence of the quantum state.</p>"""
        r"""<p>The physical behavior of this power series representation undergoes a continuous mathematical reduction in the limiting case where the coordinate displacement \( \delta x = x - x_0 \) from the expansion point is formally taken to zero. In this infinitesimal limit \( \delta x \to 0 \), all higher-order terms starting from the cubic perturbation \( \frac{1}{6} V'''(x_0)(\delta x)^3 \) decay to zero exponentially faster than the quadratic term, as their ratio scales as \( (\delta x)^n \) for \( n \ge 1 \). The infinite series collapses directly to a simple quadratic parabolic potential, recovering the standard harmonic oscillator model. Even under extreme relativistic conditions, as the ratio of velocity to the speed of light \( v/c \to 0 \), the relativistic momentum contracts to its classical form, and the dynamics reduce to standard Newtonian harmonic oscillation. By demonstrating that the complex potential series contracts smoothly to the symmetric quadratic potential as the coordinate variation is restricted, the theory establishes a mathematically consistent and physically robust link between arbitrary potential landscapes and simple linear mechanical motion.</p>"""
    )

    # 2. The Lagrangian Equations of Motion Prose
    lagrangian_equations_of_motion_html = (
        r"""<p>Derivation of the classical trajectories of a mechanical system without relying on vector force decompositions is achieved by formulating a scalar Lagrangian function of generalized coordinates and velocities. When a physical system with \( N \) degrees of freedom is analyzed, its instantaneous configuration is represented as a single point on a configuration space manifold whose coordinate paths parameterize the system's history. This elegant coordinate formulation generalizes directly to continuous systems where it generates the relativistic <strong>Field Equations</strong> of classical electromagnetism, which describe the propagation of light and charge fields across the spacetime manifold. In quantum field theory, these classical trajectories serve as the stationary phase paths in the <strong>Path Integral Formulation</strong>, where the probability amplitude is calculated by integrating the exponential of the action over all possible mathematical configurations. In the language of symplectic geometry, these coordinate systems can be mapped to phase space where the dynamics are described by <strong>The Hamiltonian Vector Field (\( X_H \))</strong>, which generates the phase flow.</p>"""
        r"""<p>To formalize this variational framework, we construct the total action functional by integrating the Lagrangian over a closed time interval, defining a scalar quantity that characterizes the global physical history of the system. The dynamic path of the system through configuration space is determined by requiring that the variation of this action is zero, a fundamental optimization principle known as the principle of <strong>Stationary Action</strong>. Under this variational principle, any virtual perturbation of the physical path \( \delta q_i(t) \) that vanishes at the temporal endpoints \( t_1 \) and \( t_2 \) must leave the action integral \( S[q] = \int_{t_1}^{t_2} L(q, \dot{q}, t) dt \) stationary. This stationary action requirement guarantees that the physical trajectory represents the natural path that extremizes the total energy difference between kinetic and potential configurations. Consequently, this variational approach bypasses the need for local coordinate forces, replacing them with a global optimization constraint that is invariant under all smooth coordinate transformations, preserving energy conservation and momentum symmetries under all coordinate shifts.</p>"""
        r"""<p>Analyzing these variational equations of motion highlights their coordinate-independent nature, which allows physicists to choose generalized coordinates \( q_i \) that match the physical symmetries of the system. For instance, in spherically symmetric potentials, employing polar coordinates \( (r, \theta, \phi) \) simplifies the Lagrangian by making certain coordinates cyclic, which directly reveals the underlying conserved quantities like angular momentum via Noether's theorem. Unlike quantum measurement theories where some interpretations rely on <strong>Consciousness-Based Collapse</strong> to collapse the wave function, the classical Lagrangian equations are completely deterministic and objective, describing the smooth evolution of mechanical configurations without observers. In gauge theories, the presence of hypothetical <strong>Magnetic Monopoles</strong> would require generalizing the vector potential \( \mathbf{A} \) to prevent singularities in the Lagrangian, demonstrating how the algebraic structure of the Lagrangian must adapt to preserve gauge symmetries. The coordinates-invariant formulation ensures that even in systems with complex geometric constraints, the equations of motion retain their identical mathematical structure, providing a unified description of subatomic forces, molecular bonds, and celestial mechanics.</p>"""
        r"""<p>The mathematical coordinates of this variational principle are formalized by applying the Euler-Lagrange equations, which translate the stationary action requirement into a set of coupled second-order differential equations. The classical Euler-Lagrange equations of motion are formulated as</p>"""
        r"""<div class="math-display" style="text-align: center; margin: 25px 0;">\[ \frac{d}{dt}\left(\frac{\partial L}{\partial \dot{q}_i}\right) - \frac{\partial L}{\partial q_i} = 0 \]</div>"""
        r"""<p>where \( L(q, \dot{q}, t) \) represents the scalar Lagrangian, \( q_i \) are the generalized coordinates, and \( \dot{q}_i \) are the generalized velocities. The physical behavior of these equations undergoes a continuous mathematical reduction in the non-relativistic, unconstrained limiting case where the generalized coordinates \( q_i \) are taken to be simple Cartesian coordinates \( x_i \), and the potential energy \( V \) depends solely on position. In this Cartesian limit, the generalized momentum \( p_i = \frac{\partial L}{\partial \dot{q}_i} \) simplifies directly to the linear momentum \( m \dot{x}_i \), and the spatial derivative \( \frac{\partial L}{\partial q_i} \) reduces to the conservative physical force \( -\frac{\partial V}{\partial x_i} \). The Lagrangian relations contract smoothly to the standard Newtonian relation \( m \ddot{x}_i = F_i \) for each independent coordinate. By demonstrating that the coordinate-invariant equations contract smoothly to Newton's second law as constraints are removed, the theory validates the mathematical continuity of the variational description, proving that the Lagrangian description is a mathematically rigorous, physically consistent, and topologically invariant generalization of Newtonian dynamics that remains valid across all classical regimes, establishing an unassailable mathematical standard for dynamic mechanical formulations.</p>"""
    )

    # 3. Orbits and Trajectories in Phase Space Prose
    phase_space_orbit_html = (
        r"""<p>Geometric formulation of a dynamical system as a continuous flow on a \( 2N \)-dimensional manifold provides a comprehensive representation of physical history, where position and momentum coordinates are treated as independent variables. When analyzing a classical system, its instantaneous state is represented as a single point in a symplectic phase space, and its time evolution traces a continuous curve. In quantum mechanics, these phase space trajectories are replaced by state vectors in <strong>Separable Hilbert Spaces</strong>, where the infinite-dimensional geometry represents the probabilities of measurement outcomes. The local flow of the state points in classical phase space is governed by the symplectic gradient of the Hamiltonian, which is represented mathematically by <strong>The Hamiltonian Vector Field (\( X_H \))</strong>. This vector field dictates the local velocity of the trajectory at every point in phase space, ensuring that the state points move along curves of constant energy, preventing any crossing of paths.</p>"""
        r"""<p>To analyze the global properties of these phase curves, we utilize the mathematical conservation laws that govern the symplectic flow on the manifold. The phase space path of a classical system can be derived by extremizing the phase space action under the principle of <strong>Least Action</strong>, which represents the physical generator of the trajectories. Under this variational framework, the volume of a closed region in phase space remains constant under time evolution, a load-bearing physical consequence of Liouville's theorem. This phase volume conservation guarantees that the trajectory flow behaves like an incompressible fluid in phase space, preventing any overlapping or crossing of phase curves for deterministic systems. This topological preservation ensures that information is never lost or duplicated during evolution, protecting the causal structure of classical mechanics under all coordinate boosts.</p>"""
        r"""<p>The mathematical coordinates of this canonical system are formalized by Hamilton's canonical equations of motion, which translate the symplectic geometry of phase space into a coupled system of first-order differential relations. Hamilton's canonical equations of motion are formulated as</p>"""
        r"""<div class="math-display" style="text-align: center; margin: 25px 0;">\[ \dot{q}_i = \frac{\partial H}{\partial p_i} \quad \text{and} \quad \dot{p}_i = -\frac{\partial H}{\partial q_i} \]</div>"""
        r"""<p>where \( q_i \) represents the generalized coordinates, \( p_i \) denotes the conjugate momenta, and \( H(q, p, t) \) is the Hamiltonian function. This canonical framework generalizes directly to continuous systems, describing the infinite-dimensional phase space of <strong>String Dynamics</strong>, where the coordinates represent the field configurations. The phase space density \( \rho(q, p) \) must satisfy a global integration constraint, a mathematical property analogous to wave function <strong>Normalization</strong> in quantum systems, ensuring that the total probability of locating the system in phase space is conserved, preventing the leakage of probability to unphysical infinity.</p>"""
        r"""<p>Analyzing the topological structure of these phase space orbits allows physicists to classify the dynamical behavior of mechanical systems into distinct regimes. In the phase portrait of a simple harmonic oscillator, the trajectories form nested closed ellipses centered at the origin, representing stable periodic orbits of constant energy \( E \). However, at extremely high energy scales where the gauge couplings of the Standard Model unify, the decay channels of hypothetical <strong>X and Y Bosons (Leptoquarks)</strong> can be modeled in phase space to determine their thermal decay rates in the early universe. The boundary between bounded oscillatory motion and unbounded running motion is represented by a separatrix, a unique phase space orbit that links unstable equilibrium points and separates distinct physical states. By studying these separatrices, physicists can identify the exact energy thresholds required for a system to escape a potential well, providing a visual and geometric method for analyzing chaotic transitions.</p>"""
        r"""<p>The physical behavior of these phase space trajectories undergoes a continuous mathematical reduction in the limiting case where the conjugate momentum \( p_i \) is explicitly decoupled from the position coordinate. In this classical coordinates-only limit, the coordinates and momenta are no longer viewed as independent variables on a symplectic manifold, and the first-order differential flow equations contract directly to second-order classical equations of motion. The two-dimensional phase space curves simplify to simple spatial trajectories parameterized by time \( t \), recovering standard configuration-space kinematics. Even under extreme relativistic conditions, as the ratio of velocity to the speed of light \( v/c \to 0 \), the relativistic momentum contracts to its classical form, and the dynamics reduce to standard Newtonian mechanics. By demonstrating that the symplectic phase flow contracts smoothly to standard configuration-space trajectories as phase dependencies are integrated out, the theory establishes a mathematically rigorous and physically consistent link between symplectic geometry and classical Newtonian mechanics.</p>"""
    )

    # Update payload
    payload["taylor-expansion-mechanics"]["content"] = taylor_expansion_mechanics_html
    payload["taylor-expansion-mechanics"]["identities"] = [
        {
            "id": "taylor-expansion-mechanics-identity-1-9fffb077",
            "title": "Taylor Series Expansion of a Physical Potential",
            "equation": r"V(x) = V(x_0) + V'(x_0)(x - x_0) + \frac{1}{2} V''(x_0)(x - x_0)^2 + \mathcal{O}((x-x_0)^3)",
            "description": "Formulates the Taylor series expansion of a physical potential energy function $V(x)$ about an arbitrary point $x_0$, establishing the mathematical foundation for the quadratic harmonic approximation."
        }
    ]

    payload["lagrangian-equations-of-motion"]["content"] = lagrangian_equations_of_motion_html
    payload["lagrangian-equations-of-motion"]["identities"] = [
        {
            "id": "lagrangian-equations-of-motion-identity-1-a6fcd874",
            "title": "Euler-Lagrange Equations of Motion",
            "equation": r"\frac{d}{dt}\left(\frac{\partial L}{\partial \dot{q}_i}\right) - \frac{\partial L}{\partial q_i} = 0",
            "description": "Formulates the classical Euler-Lagrange equations of motion for a system with generalized coordinates $q_i$, generalized velocities $\dot{q}_i$, and Lagrangian $L(q, \dot{q}, t)$, derived from the principle of stationary action."
        }
    ]

    payload["phase-space-orbit"]["content"] = phase_space_orbit_html
    payload["phase-space-orbit"]["identities"] = [
        {
            "id": "phase-space-orbit-identity-1-a501cf00",
            "title": "Hamilton's Canonical Equations of Motion",
            "equation": r"\dot{q}_i = \frac{\partial H}{\partial p_i} \quad \text{and} \quad \dot{p}_i = -\frac{\partial H}{\partial q_i}",
            "description": "Formulates Hamilton's canonical equations of motion for generalized coordinates $q_i$ and conjugate momenta $p_i$, defining the symplectic flow of trajectories in phase space."
        }
    ]

    with open("subfiles/batch_payload.json", "w") as f:
        json.dump(payload, f, indent=4)

    print("POPULATION SUCCESS: Loaded all three GQS targets into subfiles/batch_payload.json.")

if __name__ == "__main__":
    populate()
