#!/usr/bin/env python3
"""
🩹 Heal Residual Isolated Formulas
Applies physically accurate, reciprocal parent-child linkages, titles,
and conceptual definitions for the 18 residual isolated formula identities.
"""

import os
import sys
import json

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
FORMULAS_DIR = os.path.join(PROJECT_ROOT, 'app', 'config', 'content', 'formulas')

# Load all shards
shard_files = {}
all_formulas = {}
for root, dirs, files in os.walk(FORMULAS_DIR):
    for f in files:
        if f.endswith('.json') and f.startswith('shard_'):
            full_path = os.path.join(root, f)
            with open(full_path, 'r', encoding='utf-8') as fp:
                data = json.load(fp)
                shard_files[full_path] = data
                for fid, fobj in data.items():
                    if isinstance(fobj, dict):
                        all_formulas[fid] = (full_path, fobj)

heal_data = {
    'axiom-of-inertia-identity-d0045509': {
        'parent': 'conservation-of-angular-momentum-no-torque-85fdff22',
        'type': 'SPECIAL_CASE',
        'title': 'Conservation of Angular Momentum in Inertial Space',
        'conceptual_definition': 'Statement that the time derivative of total angular momentum vanishes in an unaccelerated inertial reference frame in the absence of net external torque.',
        'intuitive_summary': 'In the absence of external twisting forces, the rotational momentum of an isolated system remains permanently constant across space.',
        'interpretation': r'The time derivative $(d\mathbf{L}/dt)_{\text{space}}$ measures the change of angular momentum relative to fixed inertial axes, vanishing when no external torque acts.'
    },
    'outward-pointing-identity-8bad3206': {
        'parent': 'divergence-theorem',
        'type': 'SPECIAL_CASE',
        'title': 'Left Boundary Outward Unit Normal in One Dimension',
        'conceptual_definition': 'Orientation of the outward-pointing unit normal vector at the lower (left) endpoint of a one-dimensional spatial interval [a, b].',
        'intuitive_summary': 'Points outward into the negative coordinate direction at the left boundary of a 1D domain.',
        'interpretation': 'Ensures the 1D divergence theorem matches the fundamental theorem of calculus via oriented boundary flux evaluation.'
    },
    'outward-pointing-identity-80dfaebc': {
        'parent': 'divergence-theorem',
        'type': 'SPECIAL_CASE',
        'title': 'Right Boundary Outward Unit Normal in One Dimension',
        'conceptual_definition': 'Orientation of the outward-pointing unit normal vector at the upper (right) endpoint of a one-dimensional spatial interval [a, b].',
        'intuitive_summary': 'Points outward into the positive coordinate direction at the right boundary of a 1D domain.',
        'interpretation': 'Specifies positive outward orientation on the upper boundary manifold when integrating total outward flux in one dimension.'
    },
    'tangent-bundle-identity-ded05643': {
        'parent': 'structural-basis-e3386714',
        'type': 'SPECIAL_CASE',
        'title': 'Lie Derivative Invariance of Lagrangian Density',
        'conceptual_definition': r'Vanishing Lie derivative of the Lagrangian density along the generator vector field $\tilde{X}$ on the tangent bundle, formulating continuous symmetry.',
        'intuitive_summary': 'States that a physical system\'s Lagrangian does not change along the flow generated by a symmetry transformation.',
        'interpretation': r'Vanishing Lie derivative $\mathbb{L}_{\tilde{X}} \mathcal{L} = 0$ is the geometric condition for an exact variational symmetry under Noether\'s first theorem.'
    },
    'relativistic-larmor-identity-6e2bff84': {
        'parent': 'relativistic-larmor-7cffa0c5',
        'type': 'SPECIAL_CASE',
        'title': 'Invariant Four-Acceleration Square in Relativistic Larmor Radiation',
        'conceptual_definition': 'Lorentz scalar norm of the four-acceleration vector expressed in terms of three-dimensional velocity and acceleration vectors.',
        'intuitive_summary': 'Calculates the relativistic scalar acceleration invariant controlling radiated electromagnetic power for high-speed charges.',
        'interpretation': r'The Lorentz-invariant scalar $a^\mu a_\mu$ dictates the total power radiated by a relativistic charge in Liénard\'s generalization of Larmor\'s formula.'
    },
    'philosophy-of-physics-overview-identity-66bd92e2': {
        'parent': 'time-dependent-schrodinger-equation',
        'type': 'SPECIAL_CASE',
        'title': 'Time-Dependent Schrödinger Equation in Dirac State Space',
        'conceptual_definition': r'Fundamental equation governing the continuous, deterministic, and unitary time evolution of a quantum state vector $|\psi\rangle$.',
        'intuitive_summary': 'Describes how the quantum state ket changes continuously over time under the action of the Hamiltonian operator.',
        'interpretation': 'The Hamiltonian operator acts as the infinitesimal generator of time translations for the state vector in abstract Hilbert space.'
    },
    'geometric-quantization-identity-084012b0': {
        'parent': 'time-dependent-schrodinger-equation',
        'type': 'SPECIAL_CASE',
        'title': 'Schrödinger Evolution in Geometric Quantization',
        'conceptual_definition': 'Dynamical wave equation realized on polarized sections of a prequantum line bundle over symplectic phase space.',
        'intuitive_summary': 'Realizes the Schrödinger equation within differential geometry and geometric quantization line bundles.',
        'interpretation': 'Associates symplectic Hamiltonian vector fields with self-adjoint quantum differential operators acting on polarized wavefunction sections.'
    },
    'cosmic-expansion-identity-9210f8af': {
        'parent': 'newtons-law-of-universal-gravitation-43e95536',
        'type': 'SPECIAL_CASE',
        'title': 'Newton\'s Law of Universal Gravitation (Vector Form)',
        'conceptual_definition': 'Vector expression for the mutual attractive gravitational force exerted between two point masses separated by distance r.',
        'intuitive_summary': 'Every mass attracts every other mass with an inverse-square force directed along the line joining their centers.',
        'interpretation': r'The negative sign and radial unit vector $\mathbf{\hat{r}}$ confirm gravity is strictly attractive along the line connecting masses $m_1$ and $m_2$.'
    },
    'orthogonality-property-identity-6d5b2f73': {
        'parent': 'measurement-link-2d264282',
        'type': 'SPECIAL_CASE',
        'title': 'Initial State Projection Identity in Orthogonal Bases',
        'conceptual_definition': 'Base initialization identity setting the primary vector of an orthonormalized basis equal to the leading unnormalized state.',
        'intuitive_summary': 'Starts Gram-Schmidt orthogonalization or eigenbasis decomposition by directly selecting the first reference vector.',
        'interpretation': 'Serves as the foundation step in constructing orthogonal projection manifolds for quantum state decomposition.'
    },
    'second-variation-of-action-in-field-theory-delta-2-s-text-field-fa713255': {
        'parent': 'schwarzschild-metric',
        'type': 'LIMITING_CASE',
        'title': 'Relativistic Perihelion Precession in Schwarzschild Geometry',
        'conceptual_definition': 'Anomalous advance of perihelion per orbital revolution for an eccentric orbit around a static spherical mass in General Relativity.',
        'intuitive_summary': 'General relativistic curvature causes elliptical planetary orbits to slowly precess over each orbital revolution.',
        'interpretation': r'The non-zero precession $\Delta\phi$ arises from the non-Newtonian $1/r^3$ correction in the Schwarzschild effective potential.'
    },
    'energy-density-identity-76926752': {
        'parent': 'classical-limit-rule-3fefcb1b',
        'type': 'LIMITING_CASE',
        'title': 'Classical Limit Condition (ħ -> 0)',
        'conceptual_definition': r'The formal mathematical asymptotic limit wherein Planck\'s reduced constant $\hbar$ is treated as vanishingly small relative to macroscopic action.',
        'intuitive_summary': 'The boundary condition where quantum mechanics transitions into deterministic classical mechanics.',
        'interpretation': r'Under the limit $\hbar \to 0$, quantum commutators transition to Poisson brackets and quantum wave equations collapse onto classical Hamilton-Jacobi trajectories.'
    },
    'schwarzschild-metric-identity-447714d4': {
        'parent': 'schwarzschild-metric',
        'type': 'LIMITING_CASE',
        'title': 'Gravitational Light Deflection in Schwarzschild Spacetime',
        'conceptual_definition': 'Asymptotic bending angle of a null geodesic (light ray) passing a spherical mass M at impact parameter b in the weak-field limit.',
        'intuitive_summary': 'Predicts the exact angle by which starlight bends when grazing a massive gravitating body such as the Sun.',
        'interpretation': r'The deflection angle $\theta$ is twice the Newtonian ballistic prediction due to the equal contributions of spatial and temporal metric perturbations.'
    },
    'schwarzschild-metric-identity-34c3f77e': {
        'parent': 'schwarzschild-metric',
        'type': 'LIMITING_CASE',
        'title': 'Newtonian Potential Limit of Schwarzschild Effective Potential',
        'conceptual_definition': 'Asymptotic weak-field limit wherein the general relativistic effective potential reduces to the classical Newtonian gravitational potential.',
        'intuitive_summary': 'At large distances, general relativistic gravity converges identically to Newton\'s inverse-distance gravitational potential.',
        'interpretation': r'Confirms asymptotic recovery of Newtonian Keplerian dynamics at radial distances $r \gg r_s$ far beyond the Schwarzschild radius.'
    },
    'probability-conservation-identity-a145ff73': {
        'parent': 'hermitian-conjugate-of-an-operator-688a20a0',
        'type': 'SPECIAL_CASE',
        'title': 'Hermiticity Condition for the Quantum Hamiltonian Operator',
        'conceptual_definition': 'Self-adjointness criterion for the quantum Hamiltonian operator, guaranteeing real energy spectrum and unitary time evolution.',
        'intuitive_summary': 'A quantum Hamiltonian must equal its own conjugate transpose to ensure that total probability is strictly conserved at 100%.',
        'interpretation': r'Self-adjointness $\hat{H} = \hat{H}^\dagger$ ensures the time-evolution operator $U(t) = \exp(-i\hat{H}t/\hbar)$ is unitary, preserving inner product norms.'
    },
    'von-neumann-chain-identity-14d4a177': {
        'parent': 'von-neumann-measurement-chain-ident-accfc7c1',
        'type': 'SPECIAL_CASE',
        'title': 'Von Neumann Measurement Chain Entangled State',
        'conceptual_definition': 'Linearly entangled composite state linking the measured quantum system, measurement apparatus, and observer in Von Neumann\'s measurement formulation.',
        'intuitive_summary': 'Shows how unitary quantum evolution entangles the microscopic particle with the measuring instrument and the observer.',
        'interpretation': 'Demonstrates the measurement problem where unitary linear Schrödinger evolution propagates superposition across all macroscopic recording stages.'
    },
    'lagrangian-equations-of-motion-identity-4570a004': {
        'parent': 'form-invariance-0416c073',
        'type': 'SPECIAL_CASE',
        'title': 'Newtonian Component Equations of Motion from Lagrangian Mechanics',
        'conceptual_definition': 'Recovery of Cartesian Newton\'s second law components from the Euler-Lagrange equations for standard kinetic and potential energy forms.',
        'intuitive_summary': 'Newton\'s second law emerges directly from Lagrangian variational mechanics in Cartesian coordinates.',
        'interpretation': r'For $L = \frac{1}{2}m\sum \dot{x}_i^2 - V(x)$, the Euler-Lagrange derivative produces $m\ddot{x}_i = -\partial V/\partial x_i = F_i$.'
    },
    'stationary-action-principle-identity-091882dc': {
        'parent': 'stationarity-condition-90ce0d70',
        'type': 'DERIVED_FROM',
        'title': 'Newton\'s Second Law from Stationary Action Principle',
        'conceptual_definition': r'Newton\'s second law deduced as the stationarity condition $\delta S = 0$ of Hamilton\'s action integral along actual dynamical paths.',
        'intuitive_summary': 'A classical particle follows the exact path that minimizes or extremizes the action, producing F = ma.',
        'interpretation': 'Extreme variations of the action functional under fixed temporal boundary conditions yield the Newtonian equations of motion.'
    },
    'rotational-symmetry-identity-8bf2e205': {
        'parent': 'angular-momentum-commutation-relation-c508afc1',
        'type': 'DERIVED_FROM',
        'title': 'Hamiltonian Commutation with Total Angular Momentum Generator',
        'conceptual_definition': 'Commutation relation between the Hamiltonian and total angular momentum vector generator, expressing rotational invariance of the quantum system.',
        'intuitive_summary': 'When a system looks identical in every spatial orientation, its Hamiltonian commutes with angular momentum and total angular momentum is conserved.',
        'interpretation': r'By Ehrenfest\'s theorem and Heisenberg dynamics, $[\hat{H}, \hat{\mathbf{J}}] = 0$ implies $d\langle\mathbf{J}\rangle/dt = 0$, guaranteeing conservation of angular momentum.'
    }
}

def main():
    modified_files = set()

    for cid, info in heal_data.items():
        c_path, c_obj = all_formulas[cid]
        c_obj['parent_formula_id'] = info['parent']
        c_obj['derivation_type'] = info['type']
        c_obj['title'] = info['title']
        c_obj['conceptual_definition'] = info['conceptual_definition']
        c_obj['intuitive_summary'] = info['intuitive_summary']
        c_obj['interpretation'] = info['interpretation']
        modified_files.add(c_path)

        pid = info['parent']
        p_path, p_obj = all_formulas[pid]
        subs = p_obj.setdefault('subcomponents', [])
        if cid not in subs:
            subs.append(cid)
        modified_files.add(p_path)

    print(f'Persisting updates to {len(modified_files)} shard files...')
    for fpath in modified_files:
        with open(fpath, 'w', encoding='utf-8') as fp:
            json.dump(shard_files[fpath], fp, indent=4, ensure_ascii=False)

    print(f'✓ Successfully updated {len(heal_data)} isolated formulas across {len(modified_files)} shards.')

if __name__ == '__main__':
    main()
