/*************************************************************************
 *  tex2svg.js - MathJax 3 SSR Utility for Physics Lab
 *  Converts LaTeX formulas into static SVG paths for Hub cards.
 *************************************************************************/

const { mathjax } = require('mathjax-full/js/mathjax.js');
const { TeX } = require('mathjax-full/js/input/tex.js');
const { SVG } = require('mathjax-full/js/output/svg.js');
const { liteAdaptor } = require('mathjax-full/js/adaptors/liteAdaptor.js');
const { RegisterHTMLHandler } = require('mathjax-full/js/handlers/html.js');

const { AllPackages } = require('mathjax-full/js/input/tex/AllPackages.js');

// 1. Setup Adaptor and Handler for Node environment
const adaptor = liteAdaptor();
RegisterHTMLHandler(adaptor);

// 2. Initialize MathJax with TeX input and SVG output
const tex = new TeX({ 
    packages: AllPackages.filter(p => p !== 'bussproofs' && p !== 'physics') // Keep it clean
});
const svg = new SVG({ fontCache: 'local' });
const html = mathjax.document('', { InputJax: tex, OutputJax: svg });

// 3. Process Input
const latex = process.argv[2] || '';
const isDisplay = process.argv[3] === 'display';

if (!latex) {
    console.error('Error: No LaTeX input provided.');
    process.exit(1);
}

try {
    // 4. Convert to SVG
    const node = html.convert(latex, {
        display: isDisplay,
        em: 16,
        ex: 8,
        containerWidth: 80 * 16
    });

    // 5. Extract and Polish SVG
    let svgHtml = adaptor.innerHTML(node);
    
    // Extract the style generated by MathJax
    const styleMatch = svgHtml.match(/style="([^"]*)"/);
    const mjStyle = styleMatch ? styleMatch[1] : '';
    
    // Merge with Platinum Standard Styling (Cyan for cards)
    const finalStyle = `color: #64ffda; ${mjStyle}`;
    
    // Reconstruct the tag
    svgHtml = svgHtml.replace(/style="[^"]*"/, `style="${finalStyle}"`);
    
    process.stdout.write(svgHtml);
} catch (err) {
    console.error('MathJax Conversion Error:', err.message);
    process.exit(1);
}
